// src/components/BuyCard.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { MessageCircle, ShoppingCart, Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import { Alert } from '@/components/Alert'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { useAuth } from '@/contexts/AuthContext'
import { toast } from 'sonner'
import { getProduct } from '@/lib/firebase/db'

interface AdditionalInfo {
  name: string
  value: string
}

interface Product {
  id: string
  name: string
  description: string
  price: number
  original_price?: number
  label?: string
  category?: string
  stock_available?: boolean
  sold_count?: number
  rating?: number
  show?: boolean
  imageUrl?: string
  image?: string
  additional_information?: AdditionalInfo[]
  file?: string
}

interface BuyCardProps {
  product: Product
}

export default function BuyCard({ product: initialProduct }: BuyCardProps) {
  const { user, loading: authLoading, signInWithGoogle } = useAuth()
  const router = useRouter()

  const [product, setProduct] = useState<Product | null>(initialProduct)
  const [isLoading, setIsLoading] = useState(false)
  const [isPurchasing, setIsPurchasing] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [paymentUrl, setPaymentUrl] = useState<string | null>(null)
  const [activeTab, setActiveTab] = useState('purchase')

  // Form state
  const [purchaseFormData, setPurchaseFormData] = useState<AdditionalInfo[]>([])

  useEffect(() => {
    if (initialProduct?.additional_information && Array.isArray(initialProduct.additional_information)) {
      setPurchaseFormData(initialProduct.additional_information.map(info => ({
        name: info.name,
        value: ''
      })))
    }
    setProduct(initialProduct)
  }, [initialProduct])

  // Calculate pricing
  const TAX_PERCENT = 10
  const platformFee = product?.price ? product.price * (TAX_PERCENT / 100) : 0
  const totalPrice = (product?.price || 0) + platformFee

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('id-ID').format(value || 0)
  }

  const updatePurchaseInfo = (index: number, value: string) => {
    const newData = [...purchaseFormData]
    newData[index].value = value
    setPurchaseFormData(newData)
  }

  const openWhatsApp = () => {
    const phoneNumber = '6281359123789'
    const message = `Halo, saya ingin bertanya tentang produk: ${product?.name}`
    window.open(`https://wa.me/${phoneNumber}?text=${encodeURIComponent(message)}`, '_blank')
  }

  const handlePurchase = async () => {
    // Check if user is logged in
    if (!user && !authLoading) {
      toast.info('Login Diperlukan', {
        description: 'Silakan login terlebih dahulu untuk melakukan pembelian.'
      })
      // Save product ID to localStorage and redirect to login
      localStorage.setItem('redirectAfterLogin', '/product/' + product?.id)
      router.push('/login')
      return
    }

    // Check if product is available
    if (!product?.stock_available) {
      toast.error('Stok Habis', {
        description: 'Maaf, stok produk ini telah habis.'
      })
      return
    }

    // Validate form fields
    for (const info of purchaseFormData) {
      if (!info.value.trim()) {
        toast.error('Data Tidak Lengkap', {
          description: `Harap isi kolom "${info.name}" terlebih dahulu.`
        })
        setActiveTab('purchase')
        return
      }
    }

    setIsPurchasing(true)
    setError(null)
    setPaymentUrl(null)

    try {
      // Call payment create API
      const response = await fetch('/api/payment/create', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          productId: product?.id,
          additional_information: purchaseFormData
        })
      })

      const result = await response.json()

      if (!result.status) {
        throw new Error(result.message || 'Gagal membuat pembayaran')
      }

      // Reset form on success
      setPurchaseFormData(purchaseFormData.map(info => ({ ...info, value: '' })))

      // Show success message
      toast.success('Invoice Berhasil Dibuat', {
        description: 'Mengarahkan ke halaman pembayaran...'
      })

      // Set payment URL
      setPaymentUrl(result.data?.payment_url || result.data?.redirect_url || result.data?.qr_string || '')

      // Redirect to invoice page
      if (result.data?.redirect) {
        setTimeout(() => {
          router.push(result.data.redirect)
        }, 1500)
      }

    } catch (err: any) {
      console.error('Purchase error:', err)
      setError(err.message || 'Terjadi kesalahan saat memproses pembelian')
      toast.error('Gagal Membeli Produk', {
        description: err.message || 'Terjadi kesalahan yang tidak diketahui'
      })
    } finally {
      setIsPurchasing(false)
    }
  }

  const handleLogin = async () => {
    try {
      await signInWithGoogle()
      toast.success('Login Berhasil', {
        description: 'Anda dapat melanjutkan pembelian.'
      })
    } catch (err) {
      console.error('Login error:', err)
    }
  }

  const handlePayNow = () => {
    if (paymentUrl) {
      window.open(paymentUrl, '_blank')
    }
  }

  if (isLoading) {
    return (
      <Card className="bg-white shadow-lg sticky top-24">
        <CardContent className="p-8">
          <div className="flex items-center justify-center py-12">
            <Loader2 className="w-8 h-8 text-blue-600 animate-spin" />
            <p className="ml-3 text-slate-600">Memuat produk...</p>
          </div>
        </CardContent>
      </Card>
    )
  }

  const stockAvailable = product?.stock_available !== false && ((product?.stock_available ?? 0) > 0 || (product?.stock ?? 0) > 0)

  return (
    <Card className="bg-white shadow-lg sticky top-24">
      <CardContent className="p-6 space-y-6">
        {/* Tabs */}
        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="purchase">
              <ShoppingCart className="w-4 h-4 mr-2" />
              Pembelian
            </TabsTrigger>
            <TabsTrigger value="payment">
              <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v4a3 3 0 003 3z" />
              </svg>
              Pembayaran
            </TabsTrigger>
          </TabsList>

          {/* Purchase Tab */}
          <TabsContent value="purchase" className="space-y-6">
            {/* Price Section */}
            <div className="space-y-2">
              <h3 className="text-2xl font-bold text-blue-600">
                Rp {formatCurrency(product?.price || 0)}
              </h3>
              {product?.original_price && (
                <span className="text-base text-slate-500 line-through">
                  Rp {formatCurrency(product.original_price)}
                </span>
              )}
            </div>

            {/* Auth Status */}
            {authLoading ? (
              <div className="flex items-center gap-2 p-4 bg-blue-50 rounded-lg">
                <Loader2 className="w-5 h-5 text-blue-600 animate-spin" />
                <p className="text-sm text-slate-600">Memeriksa status login...</p>
              </div>
            ) : !user ? (
              <Alert
                variant="info"
                message="Silakan login untuk melanjutkan pembelian."
                className="!bg-blue-50 !border-blue-200 !text-blue-800"
              />
            ) : (
              <div className="flex items-center gap-2 p-4 bg-green-50 rounded-lg">
                <div className="w-5 h-5 bg-green-600 rounded-full flex items-center justify-center">
                  <svg className="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                  </svg>
                </div>
                <p className="text-sm text-slate-700">
                  Login sebagai <span className="font-semibold">{user?.displayName || user?.email}</span>
                </p>
              </div>
            )}

            {/* Purchase Form */}
            {user && stockAvailable && !paymentUrl && (
              <>
                {/* Additional Information Fields */}
                {purchaseFormData.length > 0 && (
                  <div className="space-y-4 p-4 bg-slate-50 rounded-lg">
                    <h4 className="font-semibold text-slate-800 mb-4">Lengkapi Data Pesanan</h4>
                    {purchaseFormData.map((info, index) => (
                      <div key={index} className="space-y-2">
                        <Label htmlFor={`info-${index}`}>{info.name}</Label>
                        <Input
                          id={`info-${index}`}
                          type="text"
                          value={info.value}
                          onChange={(e) => updatePurchaseInfo(index, e.target.value)}
                          placeholder={`Masukkan ${info.name}`}
                          required
                        />
                      </div>
                    ))}
                  </div>
                )}

                {/* Payment Summary */}
                <div className="space-y-3 p-4 bg-gradient-to-r from-slate-50 to-blue-50 dark:from-slate-800 dark:to-slate-900 rounded-lg">
                  <div className="flex justify-between">
                    <span className="text-slate-600 dark:text-slate-400">Harga Produk</span>
                    <span className="font-semibold text-slate-800 dark:text-slate-200">
                      Rp {formatCurrency(product?.price || 0)}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-600 dark:text-slate-400">Biaya Layanan ({TAX_PERCENT}%)</span>
                    <span className="font-semibold text-slate-800 dark:text-slate-200">
                      Rp {formatCurrency(platformFee)}
                    </span>
                  </div>
                  <div className="flex justify-between pt-3 border-t border-slate-200 dark:border-slate-700">
                    <span className="text-lg font-bold text-slate-800 dark:text-slate-200">Total</span>
                    <span className="text-xl font-bold text-blue-600">
                      Rp {formatCurrency(totalPrice)}
                    </span>
                  </div>
                </div>

                {/* Stock Status */}
                <div className="flex items-center gap-2 p-4 bg-slate-50 dark:bg-slate-800 rounded-lg">
                  <div className={`w-5 h-5 rounded-full flex items-center justify-center ${
                    product?.stock_available ? 'bg-green-600' : 'bg-red-600'
                  }`}>
                    {product?.stock_available ? (
                      <svg className="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                      </svg>
                    ) : (
                      <svg className="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M6 18L18 6M6 6l12 12" />
                      </svg>
                    )}
                  </div>
                  <span className={`font-semibold ${product?.stock_available ? 'text-green-700' : 'text-red-700'}`}>
                    {product?.stock_available ? 'Stok Tersedia' : 'Stok Habis'}
                  </span>
                </div>

                {/* Error */}
                {error && (
                  <Alert
                    variant="danger"
                    message={error}
                    dismissible
                    onClose={() => setError(null)}
                  />
                )}

                {/* Action Buttons */}
                <div className="flex flex-col sm:flex-row gap-3">
                  <Button
                    variant="outline"
                    onClick={openWhatsApp}
                    className="flex-1 border-green-600 text-green-600 hover:bg-green-50 dark:hover:bg-green-900/20"
                  >
                    <MessageCircle className="w-4 h-4 mr-2" />
                    WhatsApp
                  </Button>
                  <Button
                    onClick={handlePurchase}
                    disabled={isPurchasing || !product?.stock_available}
                    className="flex-1 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white"
                  >
                    {isPurchasing ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        <span>Memproses...</span>
                      </>
                    ) : (
                      <>
                        <ShoppingCart className="w-4 h-4 mr-2" />
                        <span>Beli Sekarang</span>
                      </>
                    )}
                  </Button>
                </div>
              </>
            )}

            {/* Login Button for non-logged in users */}
            {!user && !authLoading && (
              <div className="flex flex-col gap-3">
                <Button
                  onClick={handleLogin}
                  className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white font-semibold"
                >
                  Login dengan Google
                </Button>
                <Button
                  variant="outline"
                  onClick={openWhatsApp}
                  className="w-full border-green-600 text-green-600 hover:bg-green-50 dark:hover:bg-green-900/20"
                >
                  <MessageCircle className="w-4 h-4 mr-2" />
                  Tanya via WhatsApp
                </Button>
              </div>
            )}
          </TabsContent>

          {/* Payment Tab */}
          <TabsContent value="payment" className="space-y-6">
            {!paymentUrl ? (
              <div className="text-center py-8 space-y-4">
                <div className="w-16 h-16 mx-auto bg-slate-100 rounded-full flex items-center justify-center">
                  <svg className="w-8 h-8 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v4a3 3 0 003 3z" />
                  </svg>
                </div>
                <div className="space-y-2">
                  <h3 className="text-lg font-bold text-slate-800">Menunggu Pembayaran</h3>
                  <p className="text-slate-600">Silakan klik tombol "Beli Sekarang" terlebih dahulu untuk membuat invoice.</p>
                </div>
              </div>
            ) : (
              <div className="space-y-4">
                <div className="space-y-2">
                  <h3 className="text-lg font-bold text-slate-800">Metode Pembayaran</h3>
                  <p className="text-slate-600">Klik tombol di bawah untuk membuka halaman pembayaran Tripay.</p>
                </div>

                <Button
                  onClick={handlePayNow}
                  className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white"
                >
                  <svg className="w-5 h-5 mr-2 inline" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6h-2" />
                  </svg>
                  Bayar Sekarang
                </Button>

                <div className="p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg space-y-2">
                  <div className="flex justify-between">
                    <span className="text-slate-600 dark:text-slate-400">Total Pembayaran</span>
                    <span className="font-bold text-blue-600 dark:text-blue-400">
                      Rp {formatCurrency(totalPrice)}
                    </span>
                  </div>
                  <p className="text-xs text-slate-500 dark:text-slate-500">
                    Pembayaran akan diverifikasi otomatis oleh Tripay.
                  </p>
                </div>
              </div>
            )}
          </TabsContent>
        </Tabs>

        {/* Product Info */}
        {product && (
          <div className="pt-4 border-t border-slate-200 dark:border-slate-700">
            <div className="space-y-2 text-sm text-slate-600 dark:text-slate-400">
              <div className="flex justify-between">
                <span>Produk:</span>
                <span className="font-semibold text-slate-800 dark:text-slate-200">{product.name}</span>
              </div>
              {product.category && (
                <div className="flex justify-between">
                  <span>Kategori:</span>
                  <span className="font-semibold text-slate-800 dark:text-slate-200">{product.category}</span>
                </div>
              )}
              {product.sold_count && (
                <div className="flex justify-between">
                  <span>Terjual:</span>
                  <span className="font-semibold text-slate-800 dark:text-slate-200">{product.sold_count}</span>
                </div>
              )}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

// nuxt/components/BuyCard.vue
<template>
  <div class="buy-card">
    <!-- Price Section -->
    <div class="price-section">
      <h3 class="current-price">{{ formatCurrencyV2(product.price) }}</h3>
      <span v-if="product.original_price" class="original-price">
        {{ formatCurrencyV2(product.original_price) }}
      </span>
    </div>

    <!-- Purchase Form -->
    <form id="purchase-form" @submit.prevent="handleBuy(product._id)">
      <!-- Additional Information Fields -->
      <div v-if="purchaseFormData.length" class="additional-info">
        <h4>Lengkapi Data Pesanan</h4>
        <div v-for="(info, index) in purchaseFormData" :key="index" class="info-field">
          <label :for="`info-${index}`">{{ info.name }}</label>
          <input
            type="text"
            :id="`info-${index}`"
            v-model="info.value"
            :placeholder="`Masukkan ${info.name}`"
            required
          />
        </div>
      </div>

      <!-- Payment Summary -->
      <div class="payment-summary">
        <div class="summary-row">
          <span>Harga Produk</span>
          <span>{{ formatCurrencyV2(product.price) }}</span>
        </div>
        <div class="summary-row">
          <span>Biaya Layanan</span>
          <span>{{ formatCurrencyV2(platformFee) }}</span>
        </div>
        <div class="divider"></div>
        <div class="summary-row total">
          <span>Total</span>
          <span>{{ formatCurrencyV2(totalPrice) }}</span>
        </div>
      </div>

      <!-- Stock Status -->
      <div class="stock-status">
        <i :class="product.stock_available ? 'bi bi-check-circle' : 'bi bi-x-circle'"></i>
        <span>{{ product.stock_available ? 'Stok Tersedia' : 'Stok Habis' }}</span>
      </div>

      <!-- Action Buttons -->
      <div class="action-buttons">
        <button type="button" class="whatsapp-btn" @click="openWhatsApp">
          <i class="bi bi-whatsapp"></i>
          WhatsApp
        </button>
        <button 
          type="submit" 
          class="buy-btn"
          :disabled="isLoading || !product.stock_available"
        >
          <span v-if="isLoading" class="spinner"></span>
          <span v-else>Beli Sekarang</span>
        </button>
      </div>
    </form>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { formatCurrencyV2 } from '~/utils'
import Swal from 'sweetalert2'

const config = useRuntimeConfig()
const { $api } = useNuxtApp()

interface Product {
  _id: number | string
  name: string
  price: number
  original_price?: number
  additional_information?: string
  stock_available?: boolean
}

interface PurchaseInfo {
  name: string
  value: string
}

const props = defineProps<{ product: Product }>()

const isLoading = ref(false)
const purchaseFormData = ref<PurchaseInfo[]>([])

interface Contact {
  url: string;
}

// Open WhatsApp contact
const openWhatsApp = () => {
  const contacts = config.public.contacts as Contact[];
  if (contacts && contacts.length > 0) {
    window.open(contacts[0].url, '_blank');
  }
};

// Watch for product changes
watch(() => props.product, (newProduct) => {
  purchaseFormData.value = []
  if (newProduct?.additional_information && typeof newProduct.additional_information === 'string') {
    try {
      const parsedInfo = JSON.parse(newProduct.additional_information)
      if (Array.isArray(parsedInfo)) {
        purchaseFormData.value = parsedInfo.map(info => ({
          name: info.name,
          value: ''
        }))
      }
    } catch (e) {
      console.error('Gagal mem-parsing additional_information:', e)
    }
  }
}, { immediate: true, deep: true })

// Calculate pricing
const calculatePricingDetails = (base: number, taxPercent: number) => {
  const tax = base * (taxPercent / 100)
  return { 
    tax: Number(Math.round(tax)?.toFixed(0)), 
    total: base + tax 
  }
}

const platformFee = computed(() => 
  calculatePricingDetails(props.product.price, config.public.tax as number).tax
)

const totalPrice = computed(() => 
  Number(props.product.price) + Number(platformFee.value)
)

// Handle buy action
const handleBuy = async (productId: number | string) => {
  if (!props.product.stock_available) {
    Swal.fire({ 
      icon: 'error', 
      text: 'Maaf, stok produk ini telah habis.' 
    })
    return
  }

  // Validate form fields
  for (const info of purchaseFormData.value) {
    if (!info.value.trim()) {
      Swal.fire({ 
        icon: 'warning', 
        text: `Harap isi kolom "${info.name}" terlebih dahulu.` 
      })
      return
    }
  }

  isLoading.value = true
  try {
    const res = await $api('/api/v1/checkout', {
      method: 'POST',
      body: {
        item: productId,
        additional_information: purchaseFormData.value
      }
    })
    
    if (!res.status) throw new Error(res.msg)
    
    // Reset form on success
    purchaseFormData.value.forEach(info => info.value = '')
    
    // Redirect to payment page
    await navigateTo(res.data.redirect)
    
  } catch (error: any) {
    const msg = error?.data?.msg || 'Terjadi kesalahan yang tidak diketahui. Silakan coba lagi.'
    Swal.fire({ icon: 'error', text: msg })
  } finally {
    isLoading.value = false
  }
}
</script>

<style scoped>
.buy-card {
  background: #ffffff;
  border-radius: 8px;
  padding: 1.5rem;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
}

.price-section {
  margin-bottom: 1.5rem;
}

.current-price {
  font-size: 1.75rem;
  font-weight: 700;
  color: #2c3e50;
  margin: 0;
}

.original-price {
  font-size: 1rem;
  color: #95a5a6;
  text-decoration: line-through;
  margin-left: 0.5rem;
}

.additional-info {
  margin-bottom: 1.5rem;
}

.additional-info h4 {
  font-size: 1.1rem;
  margin-bottom: 1rem;
  color: #2c3e50;
}

.info-field {
  margin-bottom: 1rem;
}

.info-field label {
  display: block;
  margin-bottom: 0.5rem;
  font-size: 0.9rem;
  color: #7f8c8d;
}

.info-field input {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid #ddd;
  border-radius: 6px;
  font-size: 1rem;
}

.payment-summary {
  margin-bottom: 1.5rem;
}

.summary-row {
  display: flex;
  justify-content: space-between;
  margin-bottom: 0.5rem;
  font-size: 0.95rem;
}

.summary-row.total {
  font-weight: 600;
  font-size: 1.1rem;
  margin-top: 0.5rem;
}

.divider {
  height: 1px;
  background: #eee;
  margin: 0.75rem 0;
}

.stock-status {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
  font-size: 0.95rem;
}

.stock-status i {
  font-size: 1.2rem;
}

.bi-check-circle {
  color: #2ecc71;
}

.bi-x-circle {
  color: #e74c3c;
}

.action-buttons {
  display: flex;
  gap: 0.75rem;
}

.whatsapp-btn, .buy-btn {
  flex: 1;
  padding: 0.75rem;
  border-radius: 6px;
  font-weight: 500;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  cursor: pointer;
  transition: all 0.2s ease;
}

.whatsapp-btn {
  background: #25D366;
  color: white;
  border: none;
}

.whatsapp-btn:hover {
  background: #128C7E;
}

.buy-btn {
  background: #3498db;
  color: white;
  border: none;
}

.buy-btn:disabled {
  background: #bdc3c7;
  cursor: not-allowed;
}

.buy-btn:not(:disabled):hover {
  background: #2980b9;
}

.spinner {
  width: 1rem;
  height: 1rem;
  border: 2px solid rgba(255, 255, 255, 0.3);
  border-radius: 50%;
  border-top-color: white;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

@media (max-width: 768px) {
  .action-buttons {
    flex-direction: column;
  }
  
  .whatsapp-btn, .buy-btn {
    width: 100%;
  }
}
</style>
