// nuxt/pages/invoice/[id].vue
<template>
  <div class="invoice-container">
    <div class="container px-3 py-4">
      <!-- Loading State -->
      <div v-if="isLoading" class="loading-state">
        <div class="spinner-grow text-primary" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
        <p class="loading-text">Memuat invoice...</p>
      </div>

      <!-- Error State -->
      <div v-else-if="error" class="error-state">
        <div class="alert alert-danger">
          <h5><i class="bi bi-exclamation-triangle-fill me-2"></i>Gagal Memuat Data</h5>
          <p class="mb-0">{{ error }}</p>
        </div>
      </div>

      <!-- Invoice Content -->
      <div v-else-if="invoice" class="row g-4">
        <!-- QR Payment Section -->
        <div class="col-lg-5">
          <div class="payment-card">
            <div class="card-header">
              <h5><i class="bi bi-qr-code-scan me-2"></i>Pindai untuk Membayar</h5>
            </div>
            <div class="card-body">
              <div class="qr-wrapper">
                <img :src="invoice.qr" alt="QRIS Payment Code" class="qr-image">
              </div>
              
              <div v-if="countdownText" class="payment-timer alert alert-warning">
                <i class="bi bi-clock-fill me-2"></i>
                <span>Bayar sebelum: <strong>{{ countdownText }}</strong></span>
              </div>
              
              <button 
                class="btn btn-primary w-100 mt-3" 
                @click="checkPaymentStatus"
                :disabled="invoice.status === 'Lunas' || invoice.status === 'Kadaluwarsa'"
              >
                <i class="bi bi-arrow-repeat me-2"></i>Cek Status Pembayaran
              </button>
            </div>
          </div>
        </div>

        <!-- Invoice Details Section -->
        <div class="col-lg-7">
          <div class="details-card">
            <div class="card-header">
              <h4><i class="bi bi-receipt me-2"></i>Detail Transaksi</h4>
            </div>
            
            <div class="card-body">
              <!-- Transaction Status -->
              <div class="status-badge mb-4" :class="statusBadgeClass">
                {{ invoice.status }}
              </div>

              <!-- Transaction Details -->
              <div class="detail-grid">
                <div class="detail-item">
                  <span class="detail-label">ID Transaksi</span>
                  <span class="detail-value">{{ invoice.id }}</span>
                </div>
                <div class="detail-item">
                  <span class="detail-label">Email</span>
                  <span class="detail-value">{{ invoice.email }}</span>
                </div>
                <div class="detail-item">
                  <span class="detail-label">Tanggal</span>
                  <span class="detail-value">{{ formatDate(invoice.createdAt) }}</span>
                </div>
                <div class="detail-item">
                  <span class="detail-label">Metode Pembayaran</span>
                  <span class="detail-value">{{ invoice.paymentMethod.toUpperCase() }}</span>
                </div>
              </div>

              <!-- Additional Information -->
              <div v-if="invoice.additionalInformation && invoice.additionalInformation.length > 0">
                <hr class="divider">
                <h6 class="section-title"><i class="bi bi-info-circle me-2"></i>Informasi Pesanan</h6>
                <div class="detail-grid">
                  <div v-for="info in invoice.additionalInformation" :key="info.name" class="detail-item">
                    <span class="detail-label">{{ info.name }}</span>
                    <span class="detail-value">{{ info.value }}</span>
                  </div>
                </div>
              </div>

              <!-- Order Summary -->
              <hr class="divider">
              <h6 class="section-title"><i class="bi bi-cart-check me-2"></i>Ringkasan Pesanan</h6>
              <div class="order-items">
                <div v-for="item in invoice.items" :key="item.name" class="order-item">
                  <span class="item-name">{{ item.name }} <small class="text-muted">(x{{ item.quantity }})</small></span>
                  <span class="item-price">{{ formatCurrency(item.price) }}</span>
                </div>
              </div>

              <!-- Fee -->
              <div class="fee-row">
                <span class="fee-label">Biaya Penanganan</span>
                <span class="fee-value">{{ formatCurrency(invoice.fee) }}</span>
              </div>

              <!-- Total -->
              <hr class="divider">
              <div class="total-row">
                <span class="total-label">Total Pembayaran</span>
                <span class="total-amount">{{ formatCurrency(invoice.total) }}</span>
              </div>

              <!-- Download Section -->
              <div v-if="invoice.status === 'Lunas' && downloadableItems.length > 0">
                <hr class="divider">
                <h6 class="section-title"><i class="bi bi-download me-2"></i>File Download</h6>

                <div v-if="isDownloadExpired" class="alert alert-danger">
                  <i class="bi bi-exclamation-circle-fill me-2"></i>
                  Sesi unduhan telah berakhir. Silakan hubungi admin jika Anda mengalami kendala.
                </div>
                <div v-else class="download-buttons">
                  <div v-for="item in downloadableItems" :key="item.name" class="mb-2">
                    <a 
                      :href="item.file.data" 
                      :download="item.file.type === 'local'" 
                      target="_blank"
                      rel="noopener noreferrer" 
                      class="btn btn-success w-100"
                    >
                      <i class="bi bi-download me-2"></i>
                      Download {{ item.name }}
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRoute } from 'vue-router'
import Swal from 'sweetalert2'

useHead({ title: 'Invoice' })
const config = useRuntimeConfig()
const { $api } = useNuxtApp()
const route = useRoute()
const id = Array.isArray(route.params.id) ? route.params.id[0] : route.params.id

interface FileObject { type: 'local' | 'cloud'; data: string }
interface ItemWithFile extends Item { file: FileObject }
interface Item { name: string; price: number; quantity: number; file?: FileObject }
interface AdditionalInfo { name: string; value: string }
interface ApiData {
  _id: string; email: string; amount: number; items: (Item & { productId: string })[]
  qr: string; status: 'Pending' | 'Success' | 'Paid' | 'Expired'; created_at: string
  paid_at?: string; payment_method: string; additional_information?: AdditionalInfo[]
}
interface Invoice {
  id: string; status: string; email: string; createdAt: string; paidAt?: string
  expiresAt: string; items: Item[]; fee: number; total: number; qr: string
  paymentMethod: string; additionalInformation?: AdditionalInfo[]
}

const invoice = ref<Invoice | null>(null)
const isLoading = ref<boolean>(true)
const error = ref<string | null>(null)
const countdownText = ref<string>('')
const isDownloadExpired = ref(false)

let countdownInterval: NodeJS.Timeout | null = null
let paymentCheckInterval: NodeJS.Timeout | null = null
let expirationCheckInterval: NodeJS.Timeout | null = null

const downloadableItems = computed((): ItemWithFile[] => invoice.value?.items.filter((item): item is ItemWithFile => !!item.file) || [])
const statusBadgeClass = computed(() => {
  if (!invoice.value) return 'secondary'
  switch (invoice.value.status) {
    case 'Lunas': return 'success'
    case 'Kadaluwarsa': return 'danger'
    case 'Pending': return 'warning'
    default: return 'secondary'
  }
})

const formatCurrency = (value: number) => new Intl.NumberFormat('id-ID', { 
  style: 'currency', 
  currency: 'IDR', 
  minimumFractionDigits: 0 
}).format(value)

const formatDate = (dateString: string) => new Date(dateString).toLocaleString('id-ID', { 
  dateStyle: 'medium', 
  timeStyle: 'short' 
})

const padZero = (num: number) => String(num).padStart(2, '0')

const stopAllIntervals = () => {
  if (countdownInterval) clearInterval(countdownInterval)
  if (paymentCheckInterval) clearInterval(paymentCheckInterval)
  if (expirationCheckInterval) clearInterval(expirationCheckInterval)
}

const checkDownloadExpiration = () => {
  if (!invoice.value?.paidAt) return

  const expirationHours = (config.public.downloadLinkExpiresInHours as number) || 1
  const paidTimestamp = new Date(invoice.value.paidAt).getTime()
  const expirationTimestamp = paidTimestamp + (expirationHours * 60 * 60 * 1000)

  if (Date.now() > expirationTimestamp) {
    isDownloadExpired.value = true
    if (expirationCheckInterval) clearInterval(expirationCheckInterval)
  }
}

const updateCountdown = () => {
  if (!invoice.value?.expiresAt || invoice.value.status !== 'Pending') {
    stopAllIntervals()
    if (invoice.value) countdownText.value = `Status: ${invoice.value.status}`
    return
  }
  
  const now = new Date().getTime()
  const expirationTime = new Date(invoice.value.expiresAt).getTime()
  const timeDifference = expirationTime - now
  
  if (timeDifference <= 0) {
    if (invoice.value) invoice.value.status = 'Kadaluwarsa'
    countdownText.value = 'Waktu Habis'
    stopAllIntervals()
    return
  }
  
  const minutes = Math.floor((timeDifference % (1000 * 60 * 60)) / (1000 * 60))
  const seconds = Math.floor((timeDifference % (1000 * 60)) / 1000)
  countdownText.value = `${padZero(minutes)}:${padZero(seconds)}`
}

const pollPaymentStatus = async (isManual: boolean = false) => {
  if (!invoice.value || invoice.value.status !== 'Pending') return
  
  if (isManual) {
    Swal.fire({ 
      title: 'Mengecek status...', 
      didOpen: () => Swal.showLoading(), 
      allowOutsideClick: false 
    })
  }
  
  try {
    const response = await $api('/api/v1/check', { 
      method: 'POST', 
      body: { id: invoice.value.id } 
    })
    
    if (response.status) {
      await fetchInvoice()
      Swal.close()
      Swal.fire({
        title: 'Pembayaran Berhasil!',
        text: 'Terima kasih telah melakukan pembayaran.',
        icon: 'success',
        confirmButtonText: 'OK'
      })
    } else if (isManual) {
      Swal.fire({
        title: 'Masih Pending',
        text: 'Pembayaran untuk invoice ini belum terdeteksi.',
        icon: 'info',
        confirmButtonText: 'Mengerti'
      })
    }
  } catch (err) {
    if (isManual) {
      Swal.fire({
        title: 'Error',
        text: 'Gagal menghubungi server untuk cek status.',
        icon: 'error',
        confirmButtonText: 'OK'
      })
    }
  }
}

const checkPaymentStatus = () => pollPaymentStatus(true)

const fetchInvoice = async () => {
  try {
    isLoading.value = true
    const response = await $api<{ status: boolean; data: ApiData }>(`/api/v1/invoice?id=${id}`)
    
    if (!response || !response.status || !response.data) {
      throw new Error('Invoice tidak ditemukan.')
    }

    const apiData = response.data
    const itemsTotal = apiData.items?.reduce((sum, item) => sum + (Number(item.price) * item.quantity), 0)
    const calculatedFee = apiData.amount - itemsTotal
    const createdAt = new Date(apiData.created_at)
    const expiresAt = new Date(createdAt.getTime() + 10 * 60 * 1000).toISOString()

    invoice.value = {
      id: apiData._id,
      status: apiData.status === 'Paid' ? 'Lunas' : apiData.status,
      email: apiData.email,
      createdAt: apiData.created_at,
      paidAt: apiData.paid_at,
      expiresAt: expiresAt,
      items: apiData.items.map(item => ({ ...item })),
      fee: calculatedFee,
      total: apiData.amount,
      qr: apiData.qr,
      paymentMethod: apiData.payment_method,
      additionalInformation: apiData.additional_information || []
    }

    stopAllIntervals()

    if (invoice.value.status === 'Pending') {
      updateCountdown()
      countdownInterval = setInterval(updateCountdown, 1000)
      paymentCheckInterval = setInterval(() => pollPaymentStatus(false), 5000)
    } else if (invoice.value.status === 'Lunas') {
      checkDownloadExpiration()
      expirationCheckInterval = setInterval(checkDownloadExpiration, 60000)
    }

  } catch (e: any) {
    console.error(e)
    error.value = e.data?.message || "Gagal memuat detail invoice."
    stopAllIntervals()
  } finally {
    isLoading.value = false
  }
}

onMounted(fetchInvoice)
onUnmounted(stopAllIntervals)
</script>

<style scoped>
.invoice-container {
  background-color: #f8f9fa;
  min-height: 100vh;
}

.loading-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 300px;
  gap: 1rem;
}

.spinner-grow {
  width: 3rem;
  height: 3rem;
}

.loading-text {
  font-size: 1.1rem;
  color: #6c757d;
}

.error-state {
  margin-top: 2rem;
}

.error-state .alert {
  max-width: 600px;
  margin: 0 auto;
}

.payment-card, .details-card {
  background: white;
  border-radius: 12px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
  height: 100%;
}

.card-header {
  padding: 1.5rem 1.5rem 0;
  border-bottom: none;
}

.card-header h4, .card-header h5 {
  font-weight: 600;
  color: #2c3e50;
}

.card-body {
  padding: 1.5rem;
}

.qr-wrapper {
  background: white;
  padding: 1rem;
  border-radius: 8px;
  border: 1px solid #e9ecef;
  display: inline-block;
  margin-bottom: 1.5rem;
}

.qr-image {
  width: 220px;
  height: 220px;
  object-fit: contain;
}

.payment-timer {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0.5rem;
  margin-bottom: 0;
}

.status-badge {
  display: inline-block;
  padding: 0.5rem 1rem;
  border-radius: 50px;
  font-weight: 600;
  font-size: 0.9rem;
  margin-bottom: 1.5rem;
}

.status-badge.success {
  background-color: #d1fae5;
  color: #065f46;
}

.status-badge.danger {
  background-color: #fee2e2;
  color: #b91c1c;
}

.status-badge.warning {
  background-color: #fef3c7;
  color: #92400e;
}

.status-badge.secondary {
  background-color: #e5e7eb;
  color: #374151;
}

.detail-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem;
}

.detail-item {
  display: flex;
  flex-direction: column;
}

.detail-label {
  font-size: 0.85rem;
  color: #6c757d;
}

.detail-value {
  font-weight: 500;
  color: #2c3e50;
}

.section-title {
  font-weight: 600;
  color: #2c3e50;
  margin-bottom: 1rem;
}

.divider {
  border-top: 1px solid #e9ecef;
  margin: 1.5rem 0;
}

.order-items {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  margin-bottom: 1rem;
}

.order-item {
  display: flex;
  justify-content: space-between;
}

.item-name {
  color: #2c3e50;
}

.item-price {
  font-weight: 500;
  color: #2c3e50;
}

.fee-row {
  display: flex;
  justify-content: space-between;
  margin: 0.5rem 0;
}

.fee-label {
  color: #6c757d;
}

.fee-value {
  color: #6c757d;
}

.total-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 1rem;
}

.total-label {
  font-weight: 600;
  font-size: 1.1rem;
  color: #2c3e50;
}

.total-amount {
  font-weight: 700;
  font-size: 1.2rem;
  color: #1a56db;
}

.download-buttons {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.btn-primary {
  background-color: #1a56db;
  border-color: #1a56db;
}

.btn-primary:hover {
  background-color: #1649c0;
  border-color: #1649c0;
}

.btn-success {
  background-color: #057a55;
  border-color: #057a55;
}

.btn-success:hover {
  background-color: #046c4e;
  border-color: #046c4e;
}

@media (max-width: 991.98px) {
  .qr-image {
    width: 180px;
    height: 180px;
  }
  
  .detail-grid {
    grid-template-columns: 1fr;
  }
}

@media (max-width: 575.98px) {
  .card-header, .card-body {
    padding: 1.25rem;
  }
  
  .qr-wrapper {
    padding: 0.75rem;
  }
  
  .qr-image {
    width: 160px;
    height: 160px;
  }
}
</style>

// src/app/invoice/[id]/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useParams } from 'next/navigation'
import { QrCode, Clock, FileText, Download, RefreshCw, CheckCircle, XCircle, AlertTriangle, Home, ArrowLeft } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Alert } from '@/components/Alert'
import AppFooter from '@/components/AppFooter'
import { toast } from 'sonner'

interface InvoiceItem {
  name: string
  price: number
  quantity: number
  productId: string
  file?: { type: 'local' | 'cloud'; data: string }
}

interface AdditionalInfo {
  name: string
  value: string
}

interface InvoiceData {
  id: string
  email: string
  amount: number
  items: InvoiceItem[]
  qr: string
  status: 'Pending' | 'Paid' | 'Expired' | 'Failed'
  created_at: string
  paid_at?: string
  payment_method: string
  additional_information?: AdditionalInfo[]
  paidAt?: string
  createdAt?: string
  expiresAt?: string
}

export default function InvoiceDetailPage() {
  const params = useParams()
  const invoiceId = params.id as string

  const [invoice, setInvoice] = useState<InvoiceData | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [isCheckingPayment, setIsCheckingPayment] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [countdownText, setCountdownText] = useState('')
  const [isDownloadExpired, setIsDownloadExpired] = useState(false)

  let countdownInterval: NodeJS.Timeout | null = null
  let paymentCheckInterval: NodeJS.Timeout | null = null
  let expirationCheckInterval: NodeJS.Timeout | null = null

  // Load invoice data
  useEffect(() => {
    if (invoiceId) {
      loadInvoice()
    }

    return () => {
      stopAllIntervals()
    }
  }, [invoiceId])

  const loadInvoice = async () => {
    setIsLoading(true)
    setError(null)
    try {
      const response = await fetch(`/api/invoices/${invoiceId}`)
      const result = await response.json()

      if (result.status && result.data) {
        const data = result.data as InvoiceData

        // Calculate expiresAt (10 minutes from created_at)
        const createdAt = new Date(data.created_at)
        const expiresAt = new Date(createdAt.getTime() + 10 * 60 * 1000).toISOString()

        const invoiceData: InvoiceData = {
          ...data,
          createdAt: data.created_at || createdAt.toISOString(),
          paidAt: data.paid_at || data.paidAt,
          expiresAt
        }

        setInvoice(invoiceData)

        // Start countdown for pending payments
        if (data.status === 'Pending') {
          updateCountdown(expiresAt)
          countdownInterval = setInterval(() => updateCountdown(expiresAt), 1000)
          paymentCheckInterval = setInterval(() => checkPaymentStatus(false), 5000)
        } else if (data.status === 'Paid' && data.paid_at) {
          // Check download expiration
          const expirationHours = 1
          const paidTimestamp = new Date(data.paid_at).getTime()
          const expirationTimestamp = paidTimestamp + (expirationHours * 60 * 60 * 1000)

          if (Date.now() > expirationTimestamp) {
            setIsDownloadExpired(true)
          } else {
            expirationCheckInterval = setInterval(() => {
              const now = Date.now()
              if (now > expirationTimestamp) {
                setIsDownloadExpired(true)
                if (expirationCheckInterval) clearInterval(expirationCheckInterval)
              }
            }, 60000)
          }
        }
      } else {
        throw new Error('Invoice tidak ditemukan')
      }
    } catch (err: any) {
      console.error('Error loading invoice:', err)
      setError(err.message || 'Gagal memuat detail invoice')
      toast.error('Gagal Memuat Invoice', {
        description: err.message || 'Terjadi kesalahan saat memuat invoice'
      })
    } finally {
      setIsLoading(false)
    }
  }

  const stopAllIntervals = () => {
    if (countdownInterval) clearInterval(countdownInterval)
    if (paymentCheckInterval) clearInterval(paymentCheckInterval)
    if (expirationCheckInterval) clearInterval(expirationCheckInterval)
    countdownInterval = null
    paymentCheckInterval = null
    expirationCheckInterval = null
  }

  const updateCountdown = (expiresAtStr: string) => {
    const now = Date.now()
    const expirationTime = new Date(expiresAtStr).getTime()
    const timeDifference = expirationTime - now

    if (timeDifference <= 0) {
      setCountdownText('Waktu Habis')
      if (invoice) {
        setInvoice({ ...invoice, status: 'Expired' })
      }
      stopAllIntervals()
      return
    }

    const minutes = Math.floor((timeDifference % (1000 * 60 * 60)) / (1000 * 60))
    const seconds = Math.floor((timeDifference % (1000 * 60)) / 1000)
    setCountdownText(`${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`)
  }

  const checkPaymentStatus = async (isManual: boolean = false) => {
    if (!invoice || invoice.status !== 'Pending') return

    if (isManual) {
      toast.loading('Mengecek status pembayaran...', { id: 'check-payment' })
    }

    try {
      // Call payment status API
      const response = await fetch(`/api/payment/${invoice.id}/status`, {
        method: 'POST'
      })
      const data = await response.json()

      if (data.status && data.data?.status === 'Paid') {
        await loadInvoice()
        toast.success('Pembayaran Berhasil!', {
          description: 'Terima kasih telah melakukan pembayaran.',
          id: 'check-payment'
        })
      } else if (isManual) {
        toast.info('Masih Pending', {
          description: 'Pembayaran untuk invoice ini belum terdeteksi. Silakan tunggu atau pindai QR code.',
          id: 'check-payment'
        })
      }
    } catch (err: any) {
      console.error('Error checking payment:', err)
      if (isManual) {
        toast.error('Gagal Mengecek Status', {
          description: err.message || 'Terjadi kesalahan',
          id: 'check-payment'
        })
      }
    }
  }

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('id-ID', {
      style: 'currency',
      currency: 'IDR',
      minimumFractionDigits: 0
    }).format(value || 0)
  }

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleString('id-ID', {
      dateStyle: 'medium',
      timeStyle: 'short'
    })
  }

  const getStatusBadge = (status: string) => {
    const variants = {
      Paid: { label: 'Lunas', variant: 'success' as const, bg: 'bg-green-100 text-green-800' },
      Paid_Lunas: { label: 'Lunas', variant: 'success' as const, bg: 'bg-green-100 text-green-800' },
      Pending: { label: 'Menunggu Pembayaran', variant: 'warning' as const, bg: 'bg-yellow-100 text-yellow-800' },
      Expired: { label: 'Kadaluwarsa', variant: 'destructive' as const, bg: 'bg-red-100 text-red-800' },
      Failed: { label: 'Gagal', variant: 'destructive' as const, bg: 'bg-red-100 text-red-800' }
    }

    return variants[status as keyof typeof variants] || variants.Pending
  }

  const getStatusIcon = (status: string) => {
    const icons = {
      Paid: <CheckCircle className="w-5 h-5" />,
      Paid_Lunas: <CheckCircle className="w-5 h-5" />,
      Pending: <Clock className="w-5 h-5" />,
      Expired: <XCircle className="w-5 h-5" />,
      Failed: <XCircle className="w-5 h-5" />
    }

    return icons[status as keyof typeof icons] || <AlertTriangle className="w-5 h-5" />
  }

  const downloadableItems = invoice?.items.filter(item => item.file) || []

  const calculateFee = () => {
    const itemsTotal = invoice?.items.reduce((sum, item) => sum + (item.price * item.quantity), 0) || 0
    const total = invoice?.amount || 0
    return total - itemsTotal
  }

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-50 to-slate-100">
        <div className="text-center space-y-4">
          <div className="w-16 h-16 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mx-auto"></div>
          <p className="text-lg text-slate-600">Memuat invoice...</p>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-50 to-slate-100 p-4">
        <Card className="max-w-md w-full">
          <CardContent className="pt-6 text-center space-y-4">
            <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto">
              <XCircle className="w-8 h-8 text-red-600" />
            </div>
            <div className="space-y-2">
              <h3 className="text-xl font-bold text-slate-800">Gagal Memuat Invoice</h3>
              <p className="text-slate-600">{error}</p>
            </div>
            <div className="flex gap-3 justify-center">
              <Button
                onClick={() => window.location.reload()}
                variant="outline"
              >
                <RefreshCw className="w-4 h-4 mr-2" />
                Coba Lagi
              </Button>
              <Button
                onClick={() => window.location.href = '/'}
              >
                <Home className="w-4 h-4 mr-2" />
                Kembali ke Beranda
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    )
  }

  if (!invoice) {
    return null
  }

  const statusBadge = getStatusBadge(invoice.status)
  const fee = calculateFee()

  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-br from-slate-50 to-slate-100">
      {/* Navbar */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-slate-900/95 backdrop-blur-md border-b border-white/10">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <a
                href="/"
                className="text-xl font-bold text-white hover:text-blue-400 transition-colors"
              >
                Yilzi Digitalz
              </a>
              <Badge className="bg-gradient-to-r from-blue-600 to-indigo-600 text-white">
                Invoice
              </Badge>
            </div>
            <div className="flex items-center gap-3">
              <Button
                variant="ghost"
                size="sm"
                className="text-white hover:text-blue-400"
                onClick={() => window.location.href = '/dashboard'}
              >
                Dashboard
              </Button>
            </div>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="flex-grow pt-24">
        <div className="container mx-auto px-4 py-8">
          <div className="flex items-center gap-4 mb-6">
            <Button
              variant="outline"
              size="sm"
              onClick={() => window.location.href = '/dashboard'}
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Kembali
            </Button>
            <div>
              <h1 className="text-3xl font-bold text-slate-800">Detail Invoice</h1>
              <p className="text-slate-600">Invoice #{invoiceId}</p>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
            {/* QR Payment Section */}
            <div className="lg:col-span-2">
              <Card className="h-full">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <QrCode className="w-5 h-5 text-blue-600" />
                    Pindai untuk Membayar
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-6">
                  {invoice.status === 'Pending' ? (
                    <>
                      {/* QR Code */}
                      {invoice.qr && (
                        <div className="bg-white p-4 rounded-lg border border-slate-200">
                          <img
                            src={invoice.qr}
                            alt="QRIS Payment Code"
                            className="w-full h-auto rounded-md"
                          />
                        </div>
                      )}

                      {/* Timer */}
                      {countdownText && (
                        <Alert
                          variant="warning"
                          message={`Bayar sebelum: ${countdownText}`}
                          className="!bg-yellow-50 !border-yellow-200 !text-yellow-800"
                        >
                          <Clock className="w-5 h-5" />
                        </Alert>
                      )}

                      {/* Check Button */}
                      <Button
                        onClick={() => checkPaymentStatus(true)}
                        disabled={isCheckingPayment || invoice.status !== 'Pending'}
                        className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white"
                      >
                        {isCheckingPayment ? (
                          <>
                            <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin mr-2"></div>
                            Mengecek...
                          </>
                        ) : (
                          <>
                            <RefreshCw className="w-4 h-4 mr-2" />
                            Cek Status Pembayaran
                          </>
                        )}
                      </Button>

                      {/* Instructions */}
                      <div className="space-y-2 text-sm text-slate-600">
                        <p className="font-semibold">Cara Pembayaran:</p>
                        <ol className="list-decimal list-inside space-y-1">
                          <li>Scan QR code dengan aplikasi e-wallet atau M-Banking</li>
                          <li>Masukkan nominal yang sesuai</li>
                          <li>Konfirmasi pembayaran</li>
                          <li>Klik tombol "Cek Status Pembayaran"</li>
                        </ol>
                      </div>
                    </>
                  ) : (
                    <div className="text-center space-y-4 py-8">
                      <div className={`w-20 h-20 mx-auto rounded-full flex items-center justify-center ${statusBadge.bg}`}>
                        {getStatusIcon(invoice.status)}
                      </div>
                      <div>
                        <Badge className={statusBadge.bg}>{statusBadge.label}</Badge>
                      </div>
                      {invoice.status === 'Expired' && (
                        <p className="text-sm text-slate-600">
                          Waktu pembayaran telah habis. Silakan buat pesanan baru.
                        </p>
                      )}
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>

            {/* Invoice Details Section */}
            <div className="lg:col-span-3">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <FileText className="w-5 h-5 text-blue-600" />
                      Detail Transaksi
                    </div>
                    <Badge className={`${statusBadge.bg} flex items-center gap-2`}>
                      {getStatusIcon(invoice.status)}
                      {statusBadge.label}
                    </Badge>
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-6">
                  {/* Transaction Details */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-1">
                      <p className="text-sm text-slate-600">ID Transaksi</p>
                      <p className="font-semibold text-slate-800">{invoice.id}</p>
                    </div>
                    <div className="space-y-1">
                      <p className="text-sm text-slate-600">Email</p>
                      <p className="font-semibold text-slate-800">{invoice.email}</p>
                    </div>
                    <div className="space-y-1">
                      <p className="text-sm text-slate-600">Tanggal</p>
                      <p className="font-semibold text-slate-800">{formatDate(invoice.createdAt || invoice.created_at)}</p>
                    </div>
                    {invoice.paidAt && (
                      <div className="space-y-1">
                        <p className="text-sm text-slate-600">Dibayar Pada</p>
                        <p className="font-semibold text-slate-800">{formatDate(invoice.paidAt)}</p>
                      </div>
                    )}
                    <div className="space-y-1">
                      <p className="text-sm text-slate-600">Metode Pembayaran</p>
                      <p className="font-semibold text-slate-800">{invoice.payment_method?.toUpperCase()}</p>
                    </div>
                  </div>

                  {/* Additional Information */}
                  {invoice.additional_information && invoice.additional_information.length > 0 && (
                    <>
                      <div className="space-y-3">
                        <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2">
                          <FileText className="w-5 h-5" />
                          Informasi Pesanan
                        </h3>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          {invoice.additional_information.map((info, index) => (
                            <div key={index} className="space-y-1">
                              <p className="text-sm text-slate-600">{info.name}</p>
                              <p className="font-semibold text-slate-800">{info.value}</p>
                            </div>
                          ))}
                        </div>
                      </div>
                      <div className="border-t border-slate-200" />
                    </>
                  )}

                  {/* Order Summary */}
                  <div className="space-y-4">
                    <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2">
                      <FileText className="w-5 h-5" />
                      Ringkasan Pesanan
                    </h3>

                    <div className="space-y-3">
                      {invoice.items.map((item, index) => (
                        <div key={index} className="flex justify-between items-center">
                          <div className="flex-grow">
                            <p className="font-medium text-slate-800">
                              {item.name}
                              <span className="text-slate-600 text-sm ml-2">
                                (x{item.quantity})
                              </span>
                            </p>
                          </div>
                          <p className="font-semibold text-slate-800">
                            {formatCurrency(item.price)}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Fee */}
                  {fee > 0 && (
                    <div className="flex justify-between">
                      <p className="text-slate-600">Biaya Penanganan</p>
                      <p className="text-slate-800">{formatCurrency(fee)}</p>
                    </div>
                  )}

                  {/* Total */}
                  <div className="flex justify-between items-center py-4 bg-gradient-to-r from-slate-50 to-blue-50 rounded-lg px-4">
                    <p className="text-lg font-bold text-slate-800">Total Pembayaran</p>
                    <p className="text-2xl font-bold text-blue-600">
                      {formatCurrency(invoice.amount)}
                    </p>
                  </div>

                  {/* Download Section */}
                  {(invoice.status === 'Paid' || invoice.status === 'Paid_Lunas') ? (
                    <>
                      <div className="border-t border-slate-200" />
                      <div className="space-y-4">
                        <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2">
                          <Download className="w-5 h-5" />
                          File Download
                        </h3>

                        {isDownloadExpired ? (
                          <Alert
                            variant="danger"
                            message="Sesi unduhan telah berakhir. Silakan hubungi admin jika Anda mengalami kendala."
                            className="!bg-red-50 !border-red-200 !text-red-800"
                          >
                            <AlertTriangle className="w-5 h-5" />
                          </Alert>
                        ) : downloadableItems.length > 0 ? (
                          <div className="space-y-3">
                            {downloadableItems.map((item, index) => (
                              <a
                                key={index}
                                href={item.file?.data}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="block"
                              >
                                <Button className="w-full bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700 text-white">
                                  <Download className="w-4 h-4 mr-2" />
                                  Download {item.name}
                                </Button>
                              </a>
                            ))}
                          </div>
                        ) : (
                          <p className="text-slate-600 text-sm">
                            Tidak ada file yang tersedia untuk diunduh.
                          </p>
                        )}

                        {/* Download Expiration Warning */}
                        {!isDownloadExpired && invoice.paidAt && (
                          <p className="text-xs text-slate-500">
                            Link download akan kedaluwarsa dalam 1 jam setelah pembayaran.
                          </p>
                        )}
                      </div>
                    </>
                  ) : null}
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </main>

      <AppFooter />
    </div>
  )
}
