// nuxt/components/ProductList.vue
<template>
   <!-- Loading State -->
   <div v-if="isLoading" class="d-flex flex-column justify-content-center align-items-center py-5">
      <div class="spinner-border product-loader-spinner text-primary mb-3" role="status"></div>
      <p class="mb-0 text-secondary">Sedang memuat produk...</p>
   </div>

   <!-- Error State -->
   <Alert v-else-if="error" type="danger">
      {{ error }}
   </Alert>

   <!-- Produk -->
   <div v-else-if="displayedProducts.length > 0">
      <div class="row row-cols-1 row-cols-md-2 g-4">
         <div 
            v-for="product in displayedProducts" 
            :key="product._id" 
            class="col product-card-wrapper"
         >
            <div class="content-card product-item-card position-relative h-100 d-flex flex-column">
               
               <!-- Badge -->
               <div v-if="product.label" class="product-badge">
                  {{ product.label }}
               </div>

               <!-- Gambar Produk -->
               <div class="product-image-wrapper">
                  <img 
                     :src="product.imageUrl || 'https://via.placeholder.com/400x400.png?text=Produk'" 
                     class="product-image"
                     :alt="product.name"
                  >
               </div>

               <!-- Konten Produk -->
               <div class="p-3 d-flex flex-column flex-grow-1">
                  <h5 class="mb-2 product-name">{{ product.name }}</h5>

                  <div class="d-flex align-items-baseline gap-2 mb-3">
                     <span class="product-price fw-bold">
                        {{ formatCurrencyV2(product.price) }}
                     </span>
                     <span 
                        v-if="product.original_price" 
                        class="original-price"
                     >
                        {{ formatCurrencyV2(product.original_price) }}
                     </span>
                  </div>

                  <p class="small text-secondary flex-grow-1 product-description">
                     {{ createExcerpt(product.description, 120) }}
                  </p>

                  <div class="mt-auto">
                     <button 
                        @click="viewDetails(product._id)" 
                        class="btn btn-custom-accent w-100"
                     >
                        Lihat Detail Produk
                     </button>
                  </div>
               </div>
            </div>
         </div>
      </div>

      <!-- Infinite Scroll Loader -->
      <div v-if="hasMoreToShow" ref="loaderRef" class="text-center py-5">
         <div v-if="isShowingMore">
            <div class="spinner-border text-primary" role="status">
               <span class="visually-hidden">Loading...</span>
            </div>
         </div>
      </div>
   </div>

   <!-- Empty State -->
   <div v-else class="content-card text-center p-5 empty-state">
      <img src="https://cdn-icons-png.flaticon.com/512/4076/4076503.png" alt="No products" class="mb-3" width="80">
      <p class="mb-0">Tidak ada produk yang dapat ditampilkan saat ini.</p>
   </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue'
import { useRouter } from '#app'
import MarkdownIt from 'markdown-it'
import { formatCurrencyV2 } from '~/utils'

const md = new MarkdownIt()

interface Product {
   _id: number | string
   name: string
   price: number
   original_price?: number
   label?: 'Populer' | 'Baru' | string
   description: string
   imageUrl?: string
}

const { $api } = useNuxtApp()
const router = useRouter()

const allProducts = ref<Product[]>([])
const displayedProducts = ref<Product[]>([])
const isLoading = ref<boolean>(true)
const isShowingMore = ref<boolean>(false)
const error = ref<string | null>(null)
const hasMoreToShow = ref<boolean>(false)
const ITEMS_PER_BATCH = 4

const loaderRef = ref<Element | null>(null)
let observer: IntersectionObserver

const showNextBatch = () => {
   if (isShowingMore.value) return
   isShowingMore.value = true

   setTimeout(() => {
      const currentCount = displayedProducts.value.length
      const nextBatch = allProducts.value.slice(currentCount, currentCount + ITEMS_PER_BATCH)
      displayedProducts.value.push(...nextBatch)

      if (displayedProducts.value.length >= allProducts.value.length) {
         hasMoreToShow.value = false
      }

      isShowingMore.value = false
   }, 500)
}

const setupObserver = () => {
   observer = new IntersectionObserver((entries) => {
      const [entry] = entries
      if (entry.isIntersecting) {
         showNextBatch()
      }
   }, { threshold: 0.1 })

   if (loaderRef.value) {
      observer.observe(loaderRef.value)
   }
}

const createExcerpt = (markdownContent: string, maxLength: number = 120): string => {
   if (!markdownContent) return ''
   const htmlContent = md.render(markdownContent)
   const plainText = htmlContent.replace(/<[^>]*>?/gm, '')
   if (plainText.length <= maxLength) return plainText
   const truncated = plainText.substring(0, maxLength)
   const lastSpaceIndex = truncated.lastIndexOf(' ')
   return (lastSpaceIndex > 0 ? truncated.substring(0, lastSpaceIndex) : truncated) + '...'
}

const viewDetails = (productId: number | string) => {
   router.push(`/product/${productId}`)
}

onMounted(async () => {
   isLoading.value = true
   error.value = null
   try {
      const response = await $api('/api/v1/products')

      if (response && response.data) {
         allProducts.value = response.data
         displayedProducts.value = allProducts.value.slice(0, ITEMS_PER_BATCH)
         hasMoreToShow.value = allProducts.value.length > ITEMS_PER_BATCH
      } else {
         throw new Error(response.msg || 'Gagal mengambil data produk.')
      }
   } catch (e: any) {
      error.value = e.message || 'Terjadi kesalahan saat memuat produk.'
   } finally {
      isLoading.value = false
   }
})

watch(loaderRef, (newEl) => {
   if (newEl && hasMoreToShow.value) {
      setupObserver()
   }
})

onUnmounted(() => {
   if (observer) observer.disconnect()
})
</script>

<style scoped>
/* Produk Card */
.product-item-card {
   background: rgba(255, 255, 255, 0.04);
   border: 1px solid rgba(255, 255, 255, 0.08);
   border-radius: 16px;
   overflow: hidden;
   transition: all 0.35s ease;
}

.product-item-card:hover {
   transform: translateY(-4px);
   box-shadow: 0 8px 24px rgba(77, 171, 247, 0.15);
   border-color: var(--bs-primary);
}

/* Badge Produk */
.product-badge {
   position: absolute;
   top: 12px;
   left: 12px;
   background: linear-gradient(135deg, #4dabf7, #228be6);
   color: #fff;
   font-size: 0.8rem;
   font-weight: 600;
   padding: 4px 10px;
   border-radius: 6px;
   box-shadow: 0 2px 6px rgba(0,0,0,0.2);
   z-index: 2;
}

/* Gambar Produk */
.product-image-wrapper {
   width: 100%;
   overflow: hidden;
}

.product-image {
   width: 100%;
   height: 250px;
   object-fit: cover;
   transition: transform 0.4s ease;
}

.product-item-card:hover .product-image {
   transform: scale(1.05);
}

/* Nama Produk */
.product-name {
   font-size: 1.05rem;
   font-weight: 600;
   color: var(--bs-light);
}

/* Harga */
.product-price {
   font-size: 1rem;
   color: var(--bs-primary);
}

.original-price {
   font-size: 0.9rem;
   text-decoration: line-through;
   opacity: 0.6;
}

/* Empty State */
.empty-state {
   border-radius: 16px;
   background: rgba(255,255,255,0.03);
}
</style>

// src/components/ProductList.tsx
'use client'

import { useState, useEffect, useRef } from 'react'
import { useRouter } from 'next/navigation'
import Image from 'next/image'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import { Alert } from '@/components/Alert'
import { toast } from 'sonner'
import ProductCard from '@/components/ProductCard'

interface Product {
  id: string
  name: string
  description: string
  price: number
  original_price?: number
  label?: string
  imageUrl?: string
  image?: string
  stock_available?: boolean
  sold_count?: number
  rating?: number
  category?: string
  show?: boolean
}

interface ProductListProps {
  products?: Product[]
  loadFromAPI?: boolean
}

export default function ProductList({ products: initialProducts, loadFromAPI = false }: ProductListProps) {
  const router = useRouter()
  const [displayedProducts, setDisplayedProducts] = useState<Product[]>(initialProducts || [])
  const [isLoading, setIsLoading] = useState(false)
  const [isShowingMore, setIsShowingMore] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [hasMore, setHasMore] = useState(false)
  const [page, setPage] = useState(1)
  const [totalCount, setTotalCount] = useState(0)
  const ITEMS_PER_PAGE = 8

  const loaderRef = useRef<HTMLDivElement>(null)

  // Initial load
  useEffect(() => {
    if (loadFromAPI) {
      loadProducts()
    } else if (initialProducts) {
      setDisplayedProducts(initialProducts.slice(0, ITEMS_PER_PAGE))
      setHasMore(initialProducts.length > ITEMS_PER_PAGE)
      setTotalCount(initialProducts.length)
    }
  }, [initialProducts, loadFromAPI])

  // Infinite scroll with Intersection Observer
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        const [entry] = entries
        if (entry.isIntersecting && hasMore) {
          loadMore()
        }
      },
      { threshold: 0.1 }
    )

    if (loaderRef.current) {
      observer.observe(loaderRef.current)
    }

    return () => observer.disconnect()
  }, [hasMore, displayedProducts.length])

  const loadProducts = async () => {
    setIsLoading(true)
    setError(null)
    try {
      const response = await fetch(`/api/products?page=1&limit=${ITEMS_PER_PAGE}`)
      const result = await response.json()

      if (result.status && result.data) {
        const products = result.data.products || result.data || []
        setDisplayedProducts(products)
        setTotalCount(result.data.totalCount || products.length)
        setHasMore(result.data.totalCount > ITEMS_PER_PAGE)
        setPage(1)
      } else {
        throw new Error(result.message || 'Gagal mengambil data produk')
      }
    } catch (err: any) {
      console.error('Error loading products:', err)
      setError(err.message || 'Terjadi kesalahan saat memuat produk')
      toast.error('Gagal Memuat Produk', {
        description: err.message || 'Terjadi kesalahan yang tidak diketahui'
      })
    } finally {
      setIsLoading(false)
    }
  }

  const loadMore = async () => {
    if (isShowingMore) return
    setIsShowingMore(true)

    try {
      const nextPage = page + 1
      const response = await fetch(`/api/products?page=${nextPage}&limit=${ITEMS_PER_PAGE}`)
      const result = await response.json()

      if (result.status && result.data) {
        const products = result.data.products || result.data || []
        setDisplayedProducts(prev => [...prev, ...products])
        setPage(nextPage)
        setHasMore(displayedProducts.length + products.length < totalCount)
      } else {
        throw new Error(result.message || 'Gagal mengambil data produk')
      }
    } catch (err: any) {
      console.error('Error loading more products:', err)
      setError(err.message || 'Terjadi kesalahan saat memuat produk')
    } finally {
      setIsShowingMore(false)
    }
  }

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('id-ID').format(value || 0)
  }

  const truncateText = (text: string, maxLength: number) => {
    if (!text) return ''
    if (text.length <= maxLength) return text
    return text.substring(0, maxLength) + '...'
  }

  return (
    <div className="space-y-8">
      {/* Loading State */}
      {isLoading && (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {[...Array(8)].map((_, i) => (
            <Card key={i} className="overflow-hidden h-full">
              <Skeleton className="h-full w-full" />
            </Card>
          ))}
        </div>
      )}

      {/* Error State */}
      {error && (
        <Alert
          variant="danger"
          message={error}
          dismissible
          onClose={() => setError(null)}
        />
      )}

      {/* Products Grid */}
      {!isLoading && !error && displayedProducts.length > 0 && (
        <>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {displayedProducts.map((product) => (
              <ProductCard key={product.id} product={product} />
            ))}
          </div>

          {/* Load More Indicator */}
          {hasMore && (
            <div ref={loaderRef} className="text-center py-8">
              {isShowingMore ? (
                <div className="inline-flex items-center gap-2">
                  <div className="w-6 h-6 border-2 border-blue-600 border-t-transparent rounded-full animate-spin"></div>
                  <span className="text-slate-600">Memuat lebih banyak produk...</span>
                </div>
              ) : (
                <div className="h-8"></div>
              )}
            </div>
          )}

          {/* Product Count */}
          <div className="text-center text-slate-600">
            Menampilkan <span className="font-semibold text-blue-600">{displayedProducts.length}</span> dari <span className="font-semibold">{totalCount}</span> produk
          </div>
        </>
      )}

      {/* Empty State */}
      {!isLoading && !error && displayedProducts.length === 0 && (
        <Card className="text-center p-16">
          <div className="w-24 h-24 mx-auto mb-6 bg-slate-100 rounded-full flex items-center justify-center">
            <svg className="w-12 h-12 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 002 2H6a2 2 0 002-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414-2.414a1 1 0 01-.293-.707V5a2 2 0 012-2h2.586a1 1 0 001.414.586l2.414 2.414a1 1 0 01.293.707L20 12.586V10" />
            </svg>
          </div>
          <h3 className="text-2xl font-bold text-slate-800 mb-2">Tidak Ada Produk</h3>
          <p className="text-slate-600 mb-6 max-w-md mx-auto">
            {loadFromAPI
              ? 'Saat ini tidak ada produk yang tersedia.'
              : 'Tidak ada produk yang dapat ditampilkan.'}
          </p>
          <div className="flex gap-3 justify-center">
            <Button onClick={loadFromAPI ? loadProducts : () => window.location.reload()}>
              <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
              </svg>
              Refresh
            </Button>
            <Button
              variant="outline"
              onClick={() => router.push('/')}
            >
              Kembali ke Beranda
            </Button>
          </div>
        </Card>
      )}
    </div>
  )
}
