// src/app/dashboard/add-product/page.tsx
'use client'

import { useState, useRef, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, Upload, X, FileText, Link as LinkIcon, Bold, Italic, Heading2, List } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Alert } from '@/components/Alert'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Badge } from '@/components/ui/badge'
import { useAuth } from '@/contexts/AuthContext'
import { productAdd } from '@/lib/firebase/db'
import { toast } from 'sonner'
import Image from 'next/image'

interface AdditionalInfo {
  name: string
  value: string
}

export default function AddProductPage() {
  const { user, isAdmin, loading: authLoading } = useAuth()
  const router = useRouter()
  const fileInputRef = useRef<HTMLInputElement>(null)
  const productFileInputRef = useRef<HTMLInputElement>(null)

  // Form State
  const [formData, setFormData] = useState({
    name: '',
    description: '',
    price: '',
    original_price: '',
    label: '',
    category: '',
    stock_available: true,
    show: true,
    rating: 5,
    sold_count: 0
    imageUrl: '',
    image: null as File | null,
    file: null as File | string | null,
    additional_information: [] as AdditionalInfo[]
  })

  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [imagePreview, setImagePreview] = useState<string | null>(null)
  const [fileSourceType, setFileSourceType] = useState<'upload' | 'url'>('upload')
  const [activeTab, setActiveTab] = useState('product')

  // Redirect checks
  useEffect(() => {
    if (!authLoading && !user) {
      toast.error('Akses Ditolak', {
        description: 'Silakan login terlebih dahulu'
      })
      router.push('/login')
      return
    }

    if (!authLoading && user && !isAdmin) {
      toast.error('Akses Ditolak', {
        description: 'Halaman ini khusus untuk admin'
      })
      router.push('/dashboard')
      return
    }
  }, [user, isAdmin, authLoading, router])

  const formatCurrency = (value: string | number) => {
    return new Intl.NumberFormat('id-ID').format(Number(value) || 0)
  }

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file && file.size <= 5 * 1024 * 1024) { // 5MB limit
      setFormData(prev => ({ ...prev, image: file }))

      // Preview
      const reader = new FileReader()
      reader.onloadend = () => {
        setImagePreview(reader.result as string)
      }
      reader.readAsDataURL(file)
    } else if (file) {
      toast.error('Ukuran Gambar Terlalu Besar', {
        description: 'Maksimal 5MB'
      })
    }
  }

  const handleProductFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file && file.size <= 50 * 1024 * 1024) { // 50MB limit
      setFormData(prev => ({ ...prev, file }))
    } else if (file) {
      toast.error('Ukuran File Terlalu Besar', {
        description: 'Maksimal 50MB'
      })
    }
  }

  const addAdditionalInfo = () => {
    setFormData(prev => ({
      ...prev,
      additional_information: [...prev.additional_information, { name: '', value: '' }]
    }))
  }

  const removeAdditionalInfo = (index: number) => {
    setFormData(prev => ({
      ...prev,
      additional_information: prev.additional_information.filter((_, i) => i !== index)
    }))
  }

  const updateAdditionalInfo = (index: number, field: 'name' | 'value', value: string) => {
    setFormData(prev => ({
      ...prev,
      additional_information: prev.additional_information.map((info, i) =>
        i === index ? { ...info, [field]: value } : info
      )
    }))
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    // Validate required fields
    if (!formData.name.trim()) {
      toast.error('Data Tidak Lengkap', {
        description: 'Nama produk wajib diisi'
      })
      return
    }

    if (!formData.description.trim()) {
      toast.error('Data Tidak Lengkap', {
        description: 'Deskripsi produk wajib diisi'
      })
      return
    }

    if (!formData.price || Number(formData.price) <= 0) {
      toast.error('Data Tidak Lengkap', {
        description: 'Harga produk wajib diisi dengan nilai valid'
      })
      return
    }

    setIsSubmitting(true)
    setError(null)

    try {
      const productData = {
        name: formData.name.trim(),
        description: formData.description.trim(),
        price: Number(formData.price),
        original_price: formData.original_price ? Number(formData.original_price) : undefined,
        label: formData.label || undefined,
        category: formData.category || undefined,
        stock_available: formData.stock_available,
        show: formData.show,
        rating: formData.rating,
        sold_count: formData.sold_count,
        additional_information: formData.additional_information.length > 0
          ? formData.additional_information
          : undefined
      }

      // Add product to Firestore
      const result = await productAdd(productData as any)

      if (!result.status) {
        throw new Error(result.message || 'Gagal menambahkan produk')
      }

      // Upload image if exists (TODO: Firebase Storage integration)
      if (formData.image) {
        // Here you would upload to Firebase Storage
        // For now, just log
        console.log('Image to upload:', formData.image.name)
      }

      toast.success('Produk Berhasil Ditambahkan', {
        description: `"${formData.name}" telah ditambahkan ke sistem`
      })

      // Redirect to products list
      setTimeout(() => {
        router.push('/dashboard/products')
      }, 1500)

    } catch (err: any) {
      console.error('Error adding product:', err)
      setError(err.message || 'Terjadi kesalahan saat menambahkan produk')
      toast.error('Gagal Menambahkan Produk', {
        description: err.message || 'Terjadi kesalahan yang tidak diketahui'
      })
    } finally {
      setIsSubmitting(false)
    }
  }

  if (authLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="w-12 h-12 border-4 border-blue-600 border-t-transparent rounded-full animate-spin"></div>
      </div>
    )
  }

  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-br from-slate-50 to-slate-100">
      {/* Navbar */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-slate-900/95 backdrop-blur-md border-b border-white/10">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link href="/dashboard" className="text-xl font-bold text-white hover:text-blue-400 transition-colors">
                Yilzi Digitalz
              </Link>
              <Badge className="bg-gradient-to-r from-purple-600 to-pink-600 text-white">
                Admin
              </Badge>
            </div>
            <span className="text-slate-300">
              {user?.displayName || user?.email}
            </span>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="flex-grow pt-24">
        <div className="container mx-auto px-4 py-8">
          {/* Header */}
          <div className="mb-8">
            <div className="flex items-center gap-4 mb-6">
              <Link href="/dashboard/products">
                <Button variant="outline" size="sm">
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Kembali
                </Button>
              </Link>
              <div>
                <h1 className="text-3xl font-bold text-slate-800 mb-2">Tambah Produk Baru</h1>
                <p className="text-slate-600">Tambahkan produk digital baru ke toko Anda</p>
              </div>
            </div>
          </div>

          {/* Form */}
          <form onSubmit={handleSubmit}>
            <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-8">
              <TabsList className="grid w-full grid-cols-3 mb-8">
                <TabsTrigger value="product">Produk</TabsTrigger>
                <TabsTrigger value="files">Gambar & File</TabsTrigger>
                <TabsTrigger value="info">Informasi Tambahan</TabsTrigger>
              </TabsList>

              {/* Product Info Tab */}
              <TabsContent value="product" className="space-y-6">
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <FileText className="w-5 h-5 text-blue-600" />
                      Informasi Produk
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="productName">Nama Produk *</Label>
                      <Input
                        id="productName"
                        value={formData.name}
                        onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
                        placeholder="Masukkan nama produk"
                        required
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="productDescription">Deskripsi Produk *</Label>
                      <Textarea
                        id="productDescription"
                        value={formData.description}
                        onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
                        placeholder="Deskripsi lengkap produk..."
                        rows={6}
                        required
                      />
                      <p className="text-sm text-slate-500">
                        Gunakan format Markdown untuk better formatting
                      </p>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="productPrice">Harga Jual *</Label>
                        <div className="relative">
                          <span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500">
                            Rp
                          </span>
                          <Input
                            id="productPrice"
                            type="number"
                            min="0"
                            step="1000"
                            value={formData.price}
                            onChange={(e) => setFormData(prev => ({ ...prev, price: e.target.value }))}
                            placeholder="150000"
                            className="pl-10"
                            required
                          />
                        </div>
                      </div>

                      <div className="space-y-2">
                        <Label htmlFor="originalPrice">
                          Harga Asli
                          <span className="text-slate-500 ml-2">(Opsional)</span>
                        </Label>
                        <div className="relative">
                          <span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500">
                            Rp
                          </span>
                          <Input
                            id="originalPrice"
                            type="number"
                            min="0"
                            step="1000"
                            value={formData.original_price}
                            onChange={(e) => setFormData(prev => ({ ...prev, original_price: e.target.value }))}
                            placeholder="200000"
                            className="pl-10"
                          />
                        </div>
                        <p className="text-xs text-slate-500 mt-1">
                          Harga asli akan ditampilkan sebagai harga coret
                        </p>
                      </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="productBadge">Label Produk</Label>
                        <select
                          id="productBadge"
                          value={formData.label}
                          onChange={(e) => setFormData(prev => ({ ...prev, label: e.target.value }))}
                          className="w-full p-2.5 bg-white border border-slate-200 rounded-lg"
                        >
                          <option value="">-- Pilih label produk --</option>
                          <option value="Baru">Baru</option>
                          <option value="Populer">Populer</option>
                          <option value="Diskon">Diskon</option>
                          <option value="Hot Item">Hot Item</option>
                        </select>
                      </div>

                      <div className="space-y-2">
                        <Label htmlFor="productCategory">Kategori</Label>
                        <Input
                          id="productCategory"
                          value={formData.category}
                          onChange={(e) => setFormData(prev => ({ ...prev, category: e.target.value }))}
                          placeholder="Contoh: Script, Website, Bot"
                        />
                      </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <div className="flex items-center justify-between p-4 bg-slate-50 rounded-lg">
                        <div>
                          <Label htmlFor="stockAvailable" className="mb-1">Stok Tersedia</Label>
                          <p className="text-sm text-slate-600">Tampilkan produk sebagai tersedia</p>
                        </div>
                        <Switch
                          id="stockAvailable"
                          checked={formData.stock_available}
                          onCheckedChange={(checked) => setFormData(prev => ({ ...prev, stock_available: checked }))}
                        />
                      </div>

                      <div className="flex items-center justify-between p-4 bg-slate-50 rounded-lg">
                        <div>
                          <Label htmlFor="showProduct" className="mb-1">Tampilkan Produk</Label>
                          <p className="text-sm text-slate-600">Tampilkan di halaman produk</p>
                        </div>
                        <Switch
                          id="showProduct"
                          checked={formData.show}
                          onCheckedChange={(checked) => setFormData(prev => ({ ...prev, show: checked }))}
                        />
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </TabsContent>

              {/* Files Tab */}
              <TabsContent value="files" className="space-y-6">
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <Upload className="w-5 h-5 text-blue-600" />
                      Gambar & File Produk
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-6">
                    {/* Image Upload */}
                    <div className="space-y-3">
                      <Label>Gambar Produk</Label>
                      {imagePreview ? (
                        <div className="relative">
                          <Image
                            src={imagePreview}
                            alt="Preview Gambar Produk"
                            width={400}
                            height={300}
                            className="w-full h-64 object-cover rounded-lg"
                          />
                          <Button
                            type="button"
                            variant="destructive"
                            size="sm"
                            onClick={() => {
                              setImagePreview(null)
                              setFormData(prev => ({ ...prev, image: null }))
                            }}
                            className="absolute top-2 right-2"
                          >
                            <X className="w-4 h-4 mr-1" />
                            Hapus
                          </Button>
                        </div>
                      ) : (
                        <div
                          onClick={() => fileInputRef.current?.click()}
                          className="border-2 border-dashed border-slate-300 rounded-lg p-8 text-center cursor-pointer hover:border-blue-400 hover:bg-blue-50/10 transition-colors"
                        >
                          <Upload className="w-12 h-12 text-slate-400 mx-auto mb-3" />
                          <p className="text-slate-600 mb-1">Klik untuk upload gambar</p>
                          <p className="text-sm text-slate-500">Format: JPG, PNG (Maks. 5MB)</p>
                        </div>
                      )}
                      <input
                        ref={fileInputRef}
                        type="file"
                        accept="image/*"
                        onChange={handleImageChange}
                        className="hidden"
                      />
                    </div>

                    {/* Product File */}
                    <div className="space-y-3">
                      <Label>File Produk Digital</Label>
                      <div className="flex gap-2 mb-3">
                        <Button
                          type="button"
                          variant={fileSourceType === 'upload' ? 'default' : 'outline'}
                          onClick={() => setFileSourceType('upload')}
                          className="flex-1"
                        >
                          <Upload className="w-4 h-4 mr-2" />
                          Upload File
                        </Button>
                        <Button
                          type="button"
                          variant={fileSourceType === 'url' ? 'default' : 'outline'}
                          onClick={() => setFileSourceType('url')}
                          className="flex-1"
                        >
                          <LinkIcon className="w-4 h-4 mr-2" />
                          Gunakan URL
                        </Button>
                      </div>

                      {fileSourceType === 'upload' && (
                        <div>
                          {formData.file && typeof formData.file === 'object' ? (
                            <div className="p-4 bg-slate-50 rounded-lg flex items-center justify-between">
                              <div className="flex items-center gap-3 flex-grow">
                                <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center">
                                  <FileText className="w-5 h-5 text-blue-600" />
                                </div>
                                <div className="flex-grow min-w-0">
                                  <p className="font-medium text-slate-800 truncate">
                                    {(formData.file as File).name}
                                  </p>
                                  <p className="text-sm text-slate-600">
                                    {formatFileSize((formData.file as File).size)}
                                  </p>
                                </div>
                              </div>
                              <Button
                                type="button"
                                variant="ghost"
                                size="sm"
                                onClick={() => setFormData(prev => ({ ...prev, file: null }))}
                              >
                                <X className="w-4 h-4" />
                              </Button>
                            </div>
                          ) : (
                            <div
                              onClick={() => productFileInputRef.current?.click()}
                              className="border-2 border-dashed border-slate-300 rounded-lg p-8 text-center cursor-pointer hover:border-blue-400 hover:bg-blue-50/10 transition-colors"
                            >
                              <Upload className="w-12 h-12 text-slate-400 mx-auto mb-3" />
                              <p className="text-slate-600 mb-1">Klik atau seret file ke sini</p>
                              <p className="text-sm text-slate-500">Format: ZIP, PDF, dll (Maks. 50MB)</p>
                            </div>
                          )}
                          <input
                            ref={productFileInputRef}
                            type="file"
                            onChange={handleProductFileChange}
                            className="hidden"
                          />
                        </div>
                      )}

                      {fileSourceType === 'url' && (
                        <div className="space-y-2">
                          <Label htmlFor="fileUrl">Link File Produk</Label>
                          <Input
                            id="fileUrl"
                            type="url"
                            value={typeof formData.file === 'string' ? formData.file : ''}
                            onChange={(e) => setFormData(prev => ({ ...prev, file: e.target.value }))}
                            placeholder="https://contoh.com/file-produk.zip"
                          />
                        </div>
                      )}
                    </div>
                  </CardContent>
                </Card>
              </TabsContent>

              {/* Additional Info Tab */}
              <TabsContent value="info" className="space-y-6">
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <FileText className="w-5 h-5 text-blue-600" />
                      Informasi Tambahan
                    </CardTitle>
                    <p className="text-sm text-slate-600">
                      Tentukan informasi yang perlu diisi oleh pembeli saat melakukan pemesanan
                    </p>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    {formData.additional_information.map((info, index) => (
                      <div key={index} className="grid grid-cols-1 md:grid-cols-5 gap-4">
                        <div className="md:col-span-2 space-y-2">
                          <Label>Nama Label</Label>
                          <Input
                            value={info.name}
                            onChange={(e) => updateAdditionalInfo(index, 'name', e.target.value)}
                            placeholder="Contoh: ID Game, Username, dll"
                          />
                        </div>
                        <div className="md:col-span-2 space-y-2">
                          <Label>Nilai Default (Opsional)</Label>
                          <Input
                            value={info.value}
                            onChange={(e) => updateAdditionalInfo(index, 'value', e.target.value)}
                            placeholder="Nilai default"
                          />
                        </div>
                        <div className="flex items-end">
                          <Button
                            type="button"
                            variant="ghost"
                            size="sm"
                            onClick={() => removeAdditionalInfo(index)}
                            className="text-red-600 hover:bg-red-50 w-full"
                          >
                            <X className="w-4 h-4 mr-1" />
                            Hapus
                          </Button>
                        </div>
                      </div>
                    ))}

                    <Button
                      type="button"
                      variant="outline"
                      onClick={addAdditionalInfo}
                      className="w-full"
                    >
                      <Upload className="w-4 h-4 mr-2" />
                      Tambah Label Baru
                    </Button>
                  </CardContent>
                </Card>
              </TabsContent>
            </Tabs>

            {/* Error */}
            {error && (
              <Alert
                variant="danger"
                message={error}
                dismissible
                onClose={() => setError(null)}
              />
            )}

            {/* Submit Button */}
            <div className="flex justify-end">
              <Button
                type="submit"
                disabled={isSubmitting}
                className="bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white px-8"
                size="lg"
              >
                {isSubmitting ? (
                  <>
                    <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin mr-2"></div>
                    Menyimpan...
                  </>
                ) : (
                  <>
                    <FileText className="w-5 h-5 mr-2" />
                    Simpan Produk
                  </>
                )}
              </Button>
            </div>
          </form>
        </div>
      </main>

      <AppFooter />
    </div>
  )
}

function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 Bytes'
  const k = 1024
  const sizes = ['Bytes', 'KB', 'MB', 'GB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return Math.round(bytes / Math.pow(k, i) * 100) / 100 + ' ' + sizes[i]
}

// nuxt/pages/dashboard/add-product.vue
<template>
   <div class="container px-3 mb-5">
      <div class="content-card p-4 p-md-5 shadow-sm">
         <div class="d-flex align-items-center mb-4">
            <h2 class="h3 mb-0 flex-grow-1">Tambah Produk Baru</h2>
            <button type="button" class="btn btn-outline-secondary me-2" @click="$router.back()">
               <i class="bi bi-arrow-left me-1"></i> Kembali
            </button>
         </div>
         
         <form @submit.prevent="handleSubmit">
            <div class="row g-5">
               <!-- Bagian Kiri: Informasi Utama -->
               <div class="col-lg-8">
                  <div class="card border-0 shadow-sm mb-4">
                     <div class="card-header bg-light py-3">
                        <h5 class="mb-0"><i class="bi bi-info-circle me-2"></i>Informasi Produk</h5>
                     </div>
                     <div class="card-body">
                        <div class="mb-4">
                           <label for="productName" class="form-label fw-semibold">Nama Produk</label>
                           <input type="text" class="form-control form-control-lg" id="productName" 
                                  v-model="productData.name" placeholder="Masukkan nama produk" required>
                        </div>
                        
                        <div class="mb-4">
                           <label for="productDescription" class="form-label fw-semibold">Deskripsi Produk</label>
                           <div class="card border-0 bg-light">
                              <div class="card-header py-2">
                                 <div class="editor-toolbar d-flex gap-2 flex-wrap">
                                    <button type="button" class="btn btn-sm btn-outline-secondary" @click="formatText('bold')" title="Bold (Ctrl+B)">
                                       <i class="bi bi-type-bold"></i>
                                    </button>
                                    <button type="button" class="btn btn-sm btn-outline-secondary" @click="formatText('italic')" title="Italic (Ctrl+I)">
                                       <i class="bi bi-type-italic"></i>
                                    </button>
                                    <button type="button" class="btn btn-sm btn-outline-secondary" @click="formatText('heading')" title="Heading">
                                       <i class="bi bi-type-h2"></i>
                                    </button>
                                    <button type="button" class="btn btn-sm btn-outline-secondary" @click="formatText('list')" title="Unordered List">
                                       <i class="bi bi-list-ul"></i>
                                    </button>
                                    <div class="ms-auto small text-muted d-none d-md-block">Gunakan Markdown untuk format teks</div>
                                 </div>
                              </div>
                              <div class="card-body p-0">
                                 <textarea class="form-control editor-textarea border-0" id="productDescription" 
                                           rows="8" v-model="productData.description" ref="descriptionTextarea"
                                           placeholder="Deskripsi produk menggunakan format Markdown..."></textarea>
                              </div>
                           </div>
                        </div>
                        
                        <div class="row">
                           <div class="col-md-6 mb-3">
                              <label for="productPrice" class="form-label fw-semibold">Harga Jual</label>
                              <div class="input-group">
                                 <span class="input-group-text">Rp</span>
                                 <input type="number" class="form-control" id="productPrice" 
                                        v-model="productData.price" min="0" required>
                              </div>
                           </div>
                           <div class="col-md-6 mb-3">
                              <label for="originalPrice" class="form-label fw-semibold">Harga Asli <span class="text-muted">(Opsional)</span></label>
                              <div class="input-group">
                                 <span class="input-group-text">Rp</span>
                                 <input type="number" class="form-control" id="originalPrice" 
                                        v-model="productData.originalPrice" min="0" placeholder="Contoh: 500000">
                              </div>
                              <div class="form-text">Harga asli akan ditampilkan sebagai harga coret jika diisi</div>
                           </div>
                        </div>
                        
                        <div class="mb-3">
                           <label for="productBadge" class="form-label fw-semibold">Label Produk <span class="text-muted">(Opsional)</span></label>
                           <select class="form-select" id="productBadge" v-model="productData.badge">
                              <option value="">-- Pilih label produk --</option>
                              <option value="Baru">Baru</option>
                              <option value="Populer">Populer</option>
                              <option value="Diskon">Diskon</option>
                              <option value="Hot Item">Hot Item</option>
                           </select>
                        </div>
                     </div>
                  </div>
                  
                  <div class="card border-0 shadow-sm mb-4">
                     <div class="card-header bg-light py-3">
                        <h5 class="mb-0"><i class="bi bi-info-square me-2"></i>Informasi Tambahan dari Pembeli</h5>
                     </div>
                     <div class="card-body">
                        <p class="text-muted small">Tentukan informasi yang perlu diisi oleh pembeli saat melakukan pemesanan.</p>
                        
                        <div v-for="(info, index) in productData.additional_information" :key="index" 
                             class="row g-2 mb-3 align-items-center">
                           <div class="col">
                              <input type="text" class="form-control" v-model="info.name" 
                                     placeholder="Nama Label (Contoh: ID Game, Username, dll)">
                           </div>
                           <div class="col-auto">
                              <button type="button" class="btn btn-sm btn-outline-danger" 
                                      @click="removeInfo(index)" title="Hapus Label">
                                 <i class="bi bi-trash"></i>
                              </button>
                           </div>
                        </div>
                        
                        <button type="button" class="btn btn-outline-primary btn-sm" @click="addInfo">
                           <i class="bi bi-plus-circle me-1"></i> Tambah Label
                        </button>
                     </div>
                  </div>
               </div>
               
               <!-- Bagian Kanan: Upload Gambar & File -->
               <div class="col-lg-4">
                  <div class="card border-0 shadow-sm mb-4">
                     <div class="card-header bg-light py-3">
                        <h5 class="mb-0"><i class="bi bi-image me-2"></i>Gambar Produk</h5>
                     </div>
                     <div class="card-body">
                        <div v-if="imagePreviewUrl" class="image-preview-container mb-3 text-center">
                           <img :src="imagePreviewUrl" alt="Preview Gambar Produk" class="img-preview rounded shadow-sm">
                           <button type="button" class="btn btn-sm btn-danger mt-2 w-100" @click="removeImage">
                              <i class="bi bi-trash me-1"></i> Hapus Gambar
                           </button>
                        </div>
                        <div v-else class="image-upload-box text-center p-4 border rounded bg-light" 
                             @click="triggerFileInput" @dragover.prevent @drop.prevent="handleFileDrop">
                           <i class="bi bi-cloud-arrow-up display-5 text-muted mb-2"></i>
                           <p class="text-muted small mb-0">Klik atau seret gambar ke sini</p>
                           <p class="text-muted small">Format: JPG, PNG (Maks. 5MB)</p>
                        </div>
                        <input type="file" ref="fileInput" @change="handleFileChange" accept="image/*" class="d-none">
                     </div>
                  </div>
                  
                  <div class="card border-0 shadow-sm">
                     <div class="card-header bg-light py-3">
                        <h5 class="mb-0"><i class="bi bi-file-earmark me-2"></i>File Produk</h5>
                     </div>
                     <div class="card-body">
                        <p class="text-muted small mb-3">Sediakan file digital yang akan diterima pembeli.</p>
                        
                        <ul class="nav nav-pills mb-3">
                           <li class="nav-item me-2">
                              <button class="nav-link" :class="{ active: fileSourceType === 'upload' }" 
                                      type="button" @click="setFileSourceType('upload')">
                                 <i class="bi bi-upload me-1"></i> Upload File
                              </button>
                           </li>
                           <li class="nav-item">
                              <button class="nav-link" :class="{ active: fileSourceType === 'url' }" 
                                      type="button" @click="setFileSourceType('url')">
                                 <i class="bi bi-link-45deg me-1"></i> Gunakan URL
                              </button>
                           </li>
                        </ul>
                        
                        <div v-if="fileSourceType === 'upload'">
                           <div class="mb-3">
                              <label class="form-label small fw-semibold">Tujuan Upload</label>
                              <div class="d-flex gap-3">
                                 <div class="form-check">
                                    <input class="form-check-input" type="radio" id="uploadLocal" 
                                           value="local" v-model="uploadDestination">
                                    <label class="form-check-label small" for="uploadLocal">Local</label>
                                 </div>
                                 <div class="form-check">
                                    <input class="form-check-input" type="radio" id="uploadCloud" 
                                           value="cloud" v-model="uploadDestination">
                                    <label class="form-check-label small" for="uploadCloud">Cloud</label>
                                 </div>
                              </div>
                           </div>
                           
                           <div v-if="productData.file && typeof productData.file === 'object'" 
                                class="file-preview p-3 border rounded bg-light mb-3">
                              <div class="d-flex align-items-center">
                                 <i class="bi bi-file-earmark-zip-fill text-primary fs-4 me-2"></i>
                                 <div class="flex-grow-1 text-truncate">
                                    <p class="mb-0 small fw-medium text-truncate" :title="productData.file.name">
                                       {{ productData.file.name }}
                                    </p>
                                    <p class="mb-0 small text-muted">
                                       {{ formatFileSize(productData.file.size) }}
                                    </p>
                                 </div>
                                 <button type="button" class="btn btn-sm btn-outline-danger ms-2" 
                                         @click="removeProductFile" title="Hapus File">
                                    <i class="bi bi-trash"></i>
                                 </button>
                              </div>
                           </div>
                           <div v-else class="file-upload-box text-center p-4 border rounded bg-light" 
                                @click="triggerProductFileInput">
                              <i class="bi bi-cloud-arrow-up text-muted display-6 mb-2"></i>
                              <p class="text-muted small mb-0">Klik atau seret file ke sini</p>
                              <p class="text-muted small">Format: ZIP, PDF, dll (Maks. 50MB)</p>
                           </div>
                           <input type="file" ref="productFileInput" @change="handleProductFileChange" class="d-none">
                        </div>
                        
                        <div v-if="fileSourceType === 'url'">
                           <label for="fileUrl" class="form-label small fw-semibold">Link File Produk</label>
                           <input type="url" class="form-control" id="fileUrl" v-model="productData.file" 
                                  placeholder="https://contoh.com/file-produk.zip">
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            
            <div class="sticky-bottom-bar py-4 mt-5 bg-light rounded">
               <div class="d-flex justify-content-between align-items-center">
                  <div class="text-muted small" v-if="!isFormValid">
                     Harap isi semua field yang wajib diisi
                  </div>
                  <div v-else></div>
                  <button type="submit" class="btn btn-primary btn-lg px-4" :disabled="isLoading">
                     <span v-if="isLoading" class="spinner-border spinner-border-sm me-2" role="status"></span>
                     <span v-else><i class="bi bi-check-circle me-2"></i></span>
                     {{ isLoading ? 'Menyimpan...' : 'Simpan Produk' }}
                  </button>
               </div>
            </div>
            
            <div v-if="error" class="alert alert-danger mt-4 d-flex align-items-center" role="alert">
               <i class="bi bi-exclamation-triangle-fill me-2"></i>
               <div>{{ error }}</div>
            </div>
         </form>
      </div>
   </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useNuxtApp } from '#app'
import Swal from 'sweetalert2'

interface AdditionalInfo { name: string }

interface ProductFormData {
   name: string
   description: string
   price: number | null
   originalPrice: number | null
   badge: string
   image: File | null
   additional_information: AdditionalInfo[]
   file: File | string | null
}

const productData = reactive<ProductFormData>({
   name: '',
   description: '',
   price: null,
   originalPrice: null,
   badge: '',
   image: null,
   additional_information: [],
   file: null
})

const fileSourceType = ref('upload')
const uploadDestination = ref('local')
const productFileInput = ref<HTMLInputElement | null>(null)

const isLoading = ref(false)
const error = ref<string | null>(null)
const imagePreviewUrl = ref<string | null>(null)
const fileInput = ref<HTMLInputElement | null>(null)
const descriptionTextarea = ref<HTMLTextAreaElement | null>(null)
const router = useRouter()
const { $api } = useNuxtApp()

// Computed property untuk memeriksa kelengkapan form
const isFormValid = computed(() => {
   return productData.name && productData.price && productData.image
})

// Format ukuran file untuk ditampilkan
const formatFileSize = (bytes: number) => {
   if (bytes === 0) return '0 Bytes'
   const k = 1024
   const sizes = ['Bytes', 'KB', 'MB', 'GB']
   const i = Math.floor(Math.log(bytes) / Math.log(k))
   return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
}

const setFileSourceType = (type: 'upload' | 'url') => {
   fileSourceType.value = type
   productData.file = null
   removeProductFile()
}

const triggerProductFileInput = () => productFileInput.value?.click()

const handleProductFileChange = (event: Event) => {
   const target = event.target as HTMLInputElement
   const file = target.files?.[0] || null
   if (file) {
      // Validasi ukuran file (maksimal 50MB)
      if (file.size > 50 * 1024 * 1024) {
         Swal.fire({
            icon: 'error',
            title: 'File terlalu besar',
            text: 'Ukuran file maksimal adalah 50MB'
         })
         return
      }
      productData.file = file
   }
}

const removeProductFile = () => {
   productData.file = null
   if (productFileInput.value) {
      productFileInput.value.value = ''
   }
}

const addInfo = () => productData.additional_information.push({ name: '' })
const removeInfo = (index: number) => productData.additional_information.splice(index, 1)
const triggerFileInput = () => fileInput.value?.click()

const processFile = (file: File | null) => {
   if (file && file.type.startsWith('image/')) {
      // Validasi ukuran gambar (maksimal 5MB)
      if (file.size > 5 * 1024 * 1024) {
         Swal.fire({
            icon: 'error',
            title: 'Gambar terlalu besar',
            text: 'Ukuran gambar maksimal adalah 5MB'
         })
         return
      }
      productData.image = file
      imagePreviewUrl.value = URL.createObjectURL(file)
   }
}

const handleFileChange = (event: Event) => processFile((event.target as HTMLInputElement).files?.[0] || null)
const handleFileDrop = (event: DragEvent) => processFile(event.dataTransfer?.files[0] || null)

const removeImage = () => {
   productData.image = null
   if (imagePreviewUrl.value) URL.revokeObjectURL(imagePreviewUrl.value)
   imagePreviewUrl.value = null
   if (fileInput.value) fileInput.value.value = ''
}

const formatText = (type: 'bold' | 'italic' | 'heading' | 'list') => {
   const textarea = descriptionTextarea.value
   if (!textarea) return
   
   const start = textarea.selectionStart
   const end = textarea.selectionEnd
   const selectedText = textarea.value.substring(start, end)
   let replacement = ''
   
   switch (type) {
      case 'bold': 
         replacement = `**${selectedText}**`
         break
      case 'italic': 
         replacement = `*${selectedText}*`
         break
      case 'heading': 
         const startOfLine = textarea.value.lastIndexOf('\n', start - 1) + 1
         const lineText = textarea.value.substring(startOfLine, end)
         replacement = `## ${lineText}`
         textarea.setSelectionRange(startOfLine, end)
         break
      case 'list': 
         const lines = selectedText.split('\n')
         replacement = lines.map(line => `- ${line}`).join('\n')
         break
   }
   
   textarea.setRangeText(replacement, textarea.selectionStart, textarea.selectionEnd, 'end')
   productData.description = textarea.value
   textarea.focus()
}

const handleSubmit = async () => {
   isLoading.value = true
   error.value = null
   
   if (!productData.name || !productData.price || !productData.image) {
      error.value = "Nama, harga, dan gambar produk wajib diisi."
      isLoading.value = false
      
      // Scroll ke atas untuk melihat pesan error
      window.scrollTo({ top: 0, behavior: 'smooth' })
      return
   }

   const formData = new FormData()
   formData.append('name', productData.name)
   formData.append('description', productData.description)
   formData.append('price', String(productData.price))
   
   if (productData.originalPrice) formData.append('original_price', String(productData.originalPrice))
   if (productData.badge) formData.append('badge', productData.badge)
   formData.append('image', productData.image)
   formData.append('type', 'add')

   const validInfo = productData.additional_information.filter(info => info.name.trim())
   if (validInfo.length > 0) {
      formData.append('additional_information', JSON.stringify(validInfo))
   }

   if (productData.file) {
      if (fileSourceType.value === 'upload' && typeof productData.file === 'object') {
         formData.append('file', productData.file)
         formData.append('file_upload_destination', uploadDestination.value)
      } else if (fileSourceType.value === 'url' && typeof productData.file === 'string') {
         formData.append('file_url', productData.file)
      }
   }

   try {
      const response = await $api('/api/v2/product', { method: 'POST', body: formData })
      
      // Reset form
      Object.assign(productData, { 
         name: '', 
         description: '', 
         price: null, 
         originalPrice: null, 
         badge: '', 
         image: null, 
         additional_information: [], 
         file: null 
      })
      removeImage()
      removeProductFile()
      
      if (!response.data?._id) throw new Error(response.msg)
      
      await Swal.fire({ 
         icon: 'success', 
         title: 'Berhasil!', 
         text: 'Produk telah ditambahkan.', 
         timer: 2000, 
         showConfirmButton: false 
      })
      
      // Redirect ke halaman produk atau tetap di form untuk menambah produk baru
      router.push('/products')
      
   } catch (e: any) {
      error.value = e.data?.msg || "Gagal menambahkan produk. Silakan coba lagi."
      Swal.fire({ 
         icon: 'error', 
         title: 'Gagal', 
         text: `Terjadi kesalahan: ${e.message}` 
      })
   } finally {
      isLoading.value = false
   }
}
</script>

<style scoped>
.content-card {
   background-color: #fff;
   border-radius: 12px;
}

.card {
   border-radius: 10px;
   overflow: hidden;
}

.card-header {
   border-bottom: 1px solid rgba(0,0,0,0.05);
}

.form-control, .form-select {
   border-radius: 8px;
   padding: 12px 16px;
}

.form-control:focus, .form-select:focus {
   box-shadow: 0 0 0 3px rgba(13,110,253,0.15);
}

.editor-toolbar {
   padding: 8px 12px;
   background-color: #f8f9fa;
   border-radius: 8px 8px 0 0;
}

.editor-textarea {
   min-height: 200px;
   border-radius: 0 0 8px 8px;
   resize: vertical;
}

.image-upload-box, .file-upload-box {
   border: 2px dashed #dee2e6;
   border-radius: 10px;
   cursor: pointer;
   transition: all 0.2s ease;
}

.image-upload-box:hover, .file-upload-box:hover {
   border-color: #0d6efd;
   background-color: #f8f9fa;
}

.upload-icon {
   font-size: 2rem;
}

.img-preview {
   max-width: 100%;
   max-height: 300px;
   object-fit: contain;
}

.nav-pills .nav-link {
   border-radius: 6px;
}

.nav-pills .nav-link.active {
   background-color: #0d6efd;
}

.sticky-bottom-bar {
   position: sticky;
   bottom: 20px;
   box-shadow: 0 -4px 20px rgba(0,0,0,0.05);
   z-index: 100;
}

.btn {
   border-radius: 8px;
   padding: 10px 20px;
   font-weight: 500;
}

.btn-lg {
   padding: 12px 24px;
}

.spinner-border {
   width: 1.2rem;
   height: 1.2rem;
}

.badge {
   font-size: 0.8em;
   padding: 5px 10px;
   border-radius: 20px;
}

.input-group-text {
   background-color: #f8f9fa;
}

.file-preview {
   border-radius: 8px;
}

@media (max-width: 768px) {
   .content-card {
      padding: 1.5rem;
   }
   
   .sticky-bottom-bar {
      position: relative;
      bottom: 0;
      margin-top: 2rem;
   }
}
</style>
